"""Prompt registry — the library of prompts, each addressed by id (story afe6).

The reviewer-centric model has been collapsed into a UNIFIED prompt model: every
prompt is a front-matter'd ``*.md`` file, and ``category: review`` is the EXPLICIT
flag that marks a prompt as a reviewer. :func:`get_prompt` is the single resolver
returning a :class:`Prompt`; the derived :data:`reviewers/index.json` (generated by
:func:`regenerate_prompt_index`) is the offline-testable selection catalog.

Two concerns are kept deliberately separate (the converging OSS pattern):

  * **Reviewer identity + selection rules** (id, dimension, file-glob ``applies_to``,
    whether it's a default) live in a DERIVED, versioned, testable local index
    (``reviewers/index.json``, scanned from the prompt front-matter) — so selection
    is code-reviewed and offline-testable.
  * **Prompt text is GIT-CANONICAL** (epic a88f / WS-F1): the committed prompt file
    is the single source of truth — a packaged ``reviewers/*.md`` (or a user override
    at ``.rebar/prompts/<id>.md``). **Langfuse is NEVER consulted for prompt text**
    (read-replica only); the resolved text's content hash (sha256) is returned so it
    can be embedded in traces and any divergence from a Langfuse copy is detectable.
    Rendering is **strict** — an unsupplied ``{{var}}`` raises, never a silent empty.

This module is the RESOLVER half of the prompt library: which bytes are a prompt's
bytes, the derived catalog over them, the front-matter contract, variant overlays, and
reviewer selection. What a prompt *is* — the :class:`Prompt`/:class:`Reviewer` value
types, the error vocabulary, :data:`EXECUTION_MODES`, and the ``{{var}}``/marker text
grammar — lives in the I/O-free sibling :mod:`rebar.llm.prompting.prompt_model` and is
re-exported here, so every existing import and attribute access is unchanged.

Stdlib-only.
"""

from __future__ import annotations

import json
from importlib.resources import files
from pathlib import Path

# The prompt-MODEL leaf (story deft-effortless-greatdane): what a prompt IS — its value
# types, its error vocabulary, the closed execution_mode enum, and the text grammar it is
# written in. Re-exported here so ``from rebar.llm.prompting.prompts import …``
# call-sites and ``rebar.llm.prompting.prompts.<name>`` attribute access are unchanged by
# the split — and so the resolver below keeps resolving these names out of THIS module's
# namespace, exactly as it did when the definitions lived here.
from rebar.llm.prompting.prompt_model import (
    _BASE_MARKER as _BASE_MARKER,
)
from rebar.llm.prompting.prompt_model import (
    _VAR as _VAR,
)
from rebar.llm.prompting.prompt_model import (
    EXECUTION_MODES as EXECUTION_MODES,
)
from rebar.llm.prompting.prompt_model import (
    SHARED_STANCE_PREAMBLE as SHARED_STANCE_PREAMBLE,
)
from rebar.llm.prompting.prompt_model import (
    VOLATILE_MARKER as VOLATILE_MARKER,
)
from rebar.llm.prompting.prompt_model import (
    Prompt as Prompt,
)
from rebar.llm.prompting.prompt_model import (
    PromptNotFound as PromptNotFound,
)
from rebar.llm.prompting.prompt_model import (
    Reviewer as Reviewer,
)
from rebar.llm.prompting.prompt_model import (
    ReviewerError as ReviewerError,
)
from rebar.llm.prompting.prompt_model import (
    _render_strict as _render_strict,
)
from rebar.llm.prompting.prompt_model import (
    prompt_content_hash as prompt_content_hash,
)
from rebar.llm.prompting.prompt_model import (
    shared_plan_prefix as shared_plan_prefix,
)
from rebar.llm.prompting.prompt_model import (
    split_volatile as split_volatile,
)
from rebar.llm.prompting.prompt_model import (
    strip_volatile_marker as strip_volatile_marker,
)
from rebar.llm.prompting.prompt_model import (
    template_variables as template_variables,
)
from rebar.llm.prompting.prompts_frontmatter import (
    FRONT_MATTER_KEYS as FRONT_MATTER_KEYS,
)
from rebar.llm.prompting.prompts_frontmatter import (
    PROMPT_SCHEMA_VERSION as PROMPT_SCHEMA_VERSION,
)
from rebar.llm.prompting.prompts_frontmatter import (
    PromptError as PromptError,
)
from rebar.llm.prompting.prompts_frontmatter import (
    PromptVersionError as PromptVersionError,
)
from rebar.llm.prompting.prompts_frontmatter import (
    _refuse_newer_schema_version as _refuse_newer_schema_version,
)
from rebar.llm.prompting.prompts_frontmatter import (
    _split_front_matter_raw as _split_front_matter_raw,
)
from rebar.llm.prompting.prompts_frontmatter import (
    parse_front_matter as parse_front_matter,
)
from rebar.llm.prompting.prompts_frontmatter import (
    write_front_matter as write_front_matter,
)


def _catalog_dir():
    # Anchor at the ``rebar.llm`` package explicitly: this module now lives in the
    # ``rebar.llm.prompting`` subpackage, so ``__package__`` would resolve the wrong
    # root. The packaged reviewer catalog stays a ``rebar.llm`` data dir.
    return files("rebar.llm").joinpath("reviewers")


def _index_path():
    return _catalog_dir().joinpath("index.json")


def load_catalog() -> dict[str, Reviewer]:
    """Load the DERIVED reviewer index → {id: Reviewer} (story afe6).

    Reads ``reviewers/index.json`` (generated by :func:`regenerate_prompt_index` from
    the prompt front-matter). Only ``category == "review"`` entries are reviewers, so
    the catalog is exactly the reviewer set ``select_reviewers`` operates on."""
    raw = json.loads(_index_path().read_text(encoding="utf-8"))
    out: dict[str, Reviewer] = {}
    for rid, spec in raw.items():
        if rid.startswith("_"):
            continue  # reserved key (e.g. "_generated_by") — never a phantom reviewer
        out[rid] = Reviewer(
            id=rid,
            dimension=spec.get("dimension", rid),
            title=spec.get("title", ""),
            description=spec.get("description", ""),
            langfuse_prompt=spec.get("langfuse_prompt"),
            fallback_file=spec.get("fallback_file"),
            default=bool(spec.get("default", False)),
            applies_to=list(spec.get("applies_to", [])),
        )
    return out


def _packaged_prompt_files() -> dict[str, str]:
    """Map each packaged prompt id → its ``*.md`` file name (BASE prompts only — a
    ``<id>.<variant>.md`` overlay is not an independent prompt). The id is the file
    stem with underscores normalized to dashes (``ticket_quality.md`` → ``ticket-quality``)."""
    out: dict[str, str] = {}
    for entry in _catalog_dir().iterdir():
        name = entry.name
        if not name.endswith(".md"):
            continue
        stem = name[:-3]
        if "." in stem:  # a `<id>.<variant>.md` overlay, not a base prompt
            continue
        out[stem.replace("_", "-")] = name
    return out


def get_prompt(prompt_id: str, *, repo_root=None) -> Prompt:
    """Resolve ``prompt_id`` to the unified :class:`Prompt` (story afe6).

    Resolution order: a PROJECT ``.rebar/prompts/<id>.md`` override wins over the
    built-in packaged ``reviewers/<file>.md``. Front-matter is parsed; ``is_reviewer``
    is EXPLICIT (``category == "review"``). ``text`` is the body (front-matter
    stripped). Raises :class:`PromptNotFound` for an unknown id.

    ``repo_root=None`` means **packaged prompts only** — there is deliberately NO ambient
    ``config.repo_root()`` fallback here, because an attested gate run re-roots onto a
    pinned snapshot and an ambient fallback would silently read the developer's working-tree
    prompts while reviewing pinned content. Criterion DISCOVERY *does* fall back (see
    ``rebar.llm.criteria.overlay._resolve_repo_root``); any seam that does both must
    reconcile the two roots via ``criteria.check_repo_root_agreement``."""
    # Defense-in-depth: a prompt id becomes a filesystem path component below, so a
    # traversal id (``../x``, an absolute/separatored path) must never escape the
    # prompts dir even when read paths are reached over the editor's loopback server.
    if not prompt_id or "/" in prompt_id or "\\" in prompt_id or ".." in prompt_id:
        raise PromptNotFound(f"invalid prompt id {prompt_id!r}")
    fallback_file: str | None = None
    raw: str | None = None
    if repo_root:
        user = Path(repo_root) / ".rebar" / "prompts" / f"{prompt_id}.md"
        try:
            if user.is_file():
                raw = user.read_text(encoding="utf-8")
        except OSError:
            raw = None
    packaged = _packaged_prompt_files()
    if prompt_id in packaged:
        fallback_file = packaged[prompt_id]
        if raw is None:
            raw = _catalog_dir().joinpath(fallback_file).read_text(encoding="utf-8")
    if raw is None:
        # An ACCURATE not-found message. `repo_root=None` legally means "packaged prompts
        # only" (get_prompt deliberately has NO ambient fallback — see
        # `criteria.overlay._resolve_repo_root`), so in that case `.rebar/prompts/` was
        # never consulted and claiming the id is "unknown" would be a lie: it may well
        # exist in a project the caller simply didn't hand us. Say which of the two
        # happened, and — when a root WAS supplied — name the exact path searched so the
        # author can author or fix the file. Either way keep the packaged inventory, which
        # is the actionable part for a typo'd built-in id.
        if repo_root:
            searched = str(Path(repo_root) / ".rebar" / "prompts" / f"{prompt_id}.md")
            where = f"no project prompt at {searched}"
        else:
            where = (
                "no repo root was supplied, so project prompts under .rebar/prompts were "
                "not searched"
            )
        raise PromptNotFound(
            f"unknown prompt '{prompt_id}'; {where}; known built-ins: {sorted(packaged)}"
        )
    meta, body = parse_front_matter(raw)
    category = meta.get("category")
    execution_mode = meta.get("execution_mode")
    if execution_mode is None:
        execution_mode = "agentic"  # absent → the historical tool-using default
    elif execution_mode not in EXECUTION_MODES:
        raise PromptError(
            f"prompt {prompt_id!r} declares execution_mode {execution_mode!r}; "
            f"it must be one of {EXECUTION_MODES}"
        )
    return Prompt(
        id=prompt_id,
        text=body,
        category=category,
        execution_mode=execution_mode,
        default=bool(meta.get("default", False)),
        dimension=meta.get("dimension"),
        applies_to=list(meta.get("applies_to") or []),
        inputs=meta.get("inputs"),
        outputs=meta.get("outputs"),
        langfuse_prompt=meta.get("langfuse_prompt"),
        title=meta.get("title", ""),
        description=meta.get("description", ""),
        fallback_file=fallback_file,
        file_impact=list(meta.get("file_impact") or []),
    )


def build_prompt_index(repo_root=None) -> dict[str, dict]:
    """Scan the packaged prompt front-matter → the derived index mapping (story afe6).

    For each base packaged prompt emits ``id → {dimension, title, description,
    default, langfuse_prompt, fallback_file, applies_to, category, execution_mode,
    is_reviewer}``. Only ``category == "review"`` prompts (the reviewers) populate the
    index that ``load_catalog``/``select_reviewers`` operate on. Enforces the
    cross-reviewer invariants, raising :class:`PromptError`:

      (a) EXACTLY ONE ``default: true`` reviewer (reject two defaults), and
      (b) NO dimension collision (reject duplicate ``dimension``).

    A removed prompt is simply absent from a regenerated index (RETIRE)."""
    index: dict[str, dict] = {}
    defaults: list[str] = []
    by_dimension: dict[str, str] = {}
    for pid in sorted(_packaged_prompt_files()):
        prompt = get_prompt(pid, repo_root=repo_root)
        if not prompt.is_reviewer:
            continue  # only reviewers populate the selection catalog
        if prompt.default:
            defaults.append(pid)
        dim = prompt.dimension or pid
        if dim in by_dimension:
            raise PromptError(
                f"prompt index: dimension {dim!r} is claimed by both "
                f"{by_dimension[dim]!r} and {pid!r} (no dimension collision allowed)"
            )
        by_dimension[dim] = pid
        index[pid] = {
            "dimension": dim,
            "title": prompt.title,
            "description": prompt.description,
            "default": prompt.default,
            "langfuse_prompt": prompt.langfuse_prompt,
            "fallback_file": prompt.fallback_file,
            "applies_to": list(prompt.applies_to),
            "file_impact": list(prompt.file_impact),
            "category": prompt.category,
            "execution_mode": prompt.execution_mode,
            "is_reviewer": prompt.is_reviewer,
        }
    if len(defaults) != 1:
        raise PromptError(
            f"prompt index: expected EXACTLY ONE default reviewer, found {defaults} "
            "(reject two-default / zero-default)"
        )
    return index


def build_index_document(repo_root=None) -> dict[str, object]:
    """The SERIALIZED shape of ``reviewers/index.json`` — the marker banner plus the
    pure :func:`build_prompt_index` entries (ticket 9100).

    JSON has no comment syntax, so the reserved ``_generated_by`` key is how the
    committed file announces it is derived, not authored. ``build_prompt_index``
    itself stays marker-free — its invariant tests (no two defaults, no dimension
    collision, retirement) treat every key as a prompt id, and a stray ``_``-prefixed
    key would break that. ``load_catalog`` skips ``_``-prefixed keys, so the marker
    never becomes a phantom reviewer."""
    return {
        "_generated_by": (
            "GENERATED from the packaged prompt front-matter — do not edit by hand. "
            "Regenerate with `python -m rebar.llm.prompting.prompts regenerate-index`; "
            "a CI drift gate fails the build if this file is stale."
        ),
        **build_prompt_index(repo_root=repo_root),
    }


def regenerate_prompt_index(repo_root=None) -> str:
    """Regenerate ``reviewers/index.json`` from the packaged prompt front-matter and
    write it (story afe6). Returns the canonical JSON text written. CI calls this via
    ``python -m rebar.llm.prompting.prompts`` then diffs the file for drift."""
    doc = build_index_document(repo_root=repo_root)
    text = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    path = Path(str(_index_path()))
    path.write_text(text, encoding="utf-8")
    return text


def resolve_prompt_cached(
    reviewer: Reviewer | Prompt,
    variables: dict,
    *,
    base_instructions: str,
    langfuse_cfg=None,
    repo_root=None,
    variant: str | None = None,
) -> tuple[str, str, dict]:
    """Resolve a prompt and SPLIT it for prompt caching (story c6e5) → ``(system_prefix,
    instructions, prompt_meta)``.

    The byte-stable prefix (everything before the ``<!--volatile-->`` marker — the role,
    rules, and how-to, with NO per-run variables) is the cacheable system prompt; the
    volatile per-run body (after the marker — the rendered ticket/plan/diff data) is
    folded into the user-message ``instructions`` AHEAD of ``base_instructions`` (data
    first, then the task). A prompt with NO marker yields ``(whole_text,
    base_instructions, meta)`` — exactly the pre-S2 behavior, so unmarked prompts are
    unchanged. This is the single shared seam every cache-aware RunRequest builder uses
    (RunnerAgentStep, code_review, the review op), so the split is defined once."""
    compiled, meta = resolve_prompt(
        reviewer, variables, langfuse_cfg, repo_root=repo_root, variant=variant
    )
    stable, volatile = split_volatile(compiled)
    instructions = "\n\n".join(p for p in (volatile, base_instructions) if p)
    return stable, instructions, meta


def _prompt_file(reviewer: Reviewer | Prompt, repo_root, variant: str | None):
    """The file for a reviewer's base or ``<id>.<variant>`` prompt — a user
    ``.rebar/prompts/`` override wins over the packaged ``reviewers/`` copy."""
    suffix = f".{variant}" if variant else ""
    if repo_root:
        user = Path(repo_root) / ".rebar" / "prompts" / f"{reviewer.id}{suffix}.md"
        try:
            if user.is_file():
                return user.read_text(encoding="utf-8")
        except OSError:
            pass
    if reviewer.fallback_file:
        stem = (
            reviewer.fallback_file[:-3]
            if reviewer.fallback_file.endswith(".md")
            else (reviewer.fallback_file)
        )
        pkg = _catalog_dir().joinpath(f"{stem}{suffix}.md")
        try:
            return pkg.read_text(encoding="utf-8")
        except (OSError, FileNotFoundError):
            pass
    return None


def load_prompt(
    reviewer: Reviewer | Prompt,
    *,
    repo_root=None,
    variant: str | None = None,
    _seen: set | None = None,
) -> tuple[str, dict]:
    """Resolve a reviewer's prompt to ``(body, meta)`` — front-matter stripped and
    variant overlay applied (WS-F2).

    A variant (``<id>.<variant>.md``) overlays a base: its front-matter ``variant_of``
    names the parent (default: the base), and its body may include the parent via the
    ``<!--base-->`` marker (no marker → it is a full override). The ``variant_of``
    chain is cycle-guarded."""
    _seen = _seen if _seen is not None else set()
    key = variant or "<base>"
    if key in _seen:
        raise PromptError(f"prompt variant cycle detected at {key!r} for {reviewer.id!r}")
    _seen.add(key)

    raw = _prompt_file(reviewer, repo_root, variant)
    if raw is None:
        if variant:
            raise PromptError(f"unknown prompt variant {variant!r} for reviewer {reviewer.id!r}")
        raw = ""  # a reviewer with no fallback_file resolves to empty (legacy behavior)
    meta, body = parse_front_matter(raw)

    if variant:
        parent = meta.get("variant_of")  # None → overlay onto the base
        parent_body, parent_meta = load_prompt(
            reviewer, repo_root=repo_root, variant=parent, _seen=_seen
        )
        includes_base = _BASE_MARKER in body
        if includes_base:
            body = body.replace(_BASE_MARKER, parent_body)
        merged = {**parent_meta, **meta}
        merged.pop("variant_of", None)
        # When the overlay splices the base body in, the spliced result uses BOTH
        # the base's and the variant's variables — so UNION their declared
        # `variables`/`required` rather than letting the shallow overlay drop the
        # base's (which would break parity + strict rendering of base vars). A
        # full override (no <!--base-->) keeps only the variant's own declarations.
        if includes_base:
            for k in ("variables", "required"):
                union: list = []
                for v in [*(parent_meta.get(k) or []), *(meta.get(k) or [])]:
                    if v not in union:
                        union.append(v)
                if union:
                    merged[k] = union
        return body, merged
    return body, meta


def canonical_prompt_text(
    reviewer: Reviewer | Prompt, *, repo_root=None, variant: str | None = None
) -> str:
    """The GIT-CANONICAL prompt text for a reviewer (WS-F1/F2): the committed prompt
    file's body (front-matter stripped, variant overlay applied). A user
    ``.rebar/prompts/<id>.md`` override wins over the packaged ``reviewers/*.md``;
    Langfuse is NEVER consulted."""
    return load_prompt(reviewer, repo_root=repo_root, variant=variant)[0]


def prompt_input_schema(
    reviewer: Reviewer | Prompt, *, repo_root=None, variant: str | None = None
) -> dict:
    """A JSON Schema for a prompt's declared input variables (WS-F2).

    Properties = the declared ``variables`` (string-typed); ``required`` = the
    declared required subset (or ALL declared variables when ``required`` is
    unspecified). Falls back to the template's actually-used ``{{vars}}`` when no
    front-matter declares them. ``additionalProperties`` is allowed (the engine
    supplies extra context like ``repo_path``)."""
    body, meta = load_prompt(reviewer, repo_root=repo_root, variant=variant)
    declared = list(meta.get("variables") or sorted(template_variables(body)))
    required = list(meta.get("required", declared))
    return {
        "type": "object",
        "additionalProperties": True,
        "properties": {v: {"type": "string"} for v in declared},
        "required": [r for r in required if r in declared],
    }


def check_prompt_parity(
    reviewer: Reviewer | Prompt, *, repo_root=None, variant: str | None = None
) -> list[str]:
    """Parity gate (WS-F2): diff a prompt's DECLARED front-matter ``variables`` vs the
    vars its template actually uses. A used-but-undeclared var is an error; a
    declared-but-unused var is an error. No declared front-matter → no findings (the
    template's used vars are self-declaring; the universe gate covers those)."""
    body, meta = load_prompt(reviewer, repo_root=repo_root, variant=variant)
    if "variables" not in meta:
        return []
    declared = set(meta.get("variables") or [])
    used = template_variables(body)
    errors: list[str] = []
    for v in sorted(used - declared):
        errors.append(f"variable {{{{{v}}}}} used in template but not declared in front-matter")
    for v in sorted(declared - used):
        errors.append(f"variable {v!r} declared in front-matter but unused in template")
    bad_required = set(meta.get("required") or []) - declared
    for v in sorted(bad_required):
        errors.append(f"required variable {v!r} is not in declared variables")
    return errors


def prompt_ref_exists(prompt_id: str, *, repo_root=None) -> bool:
    """True if a workflow ``prompt:`` ref resolves to a real prompt (WS-F2): a known
    catalog reviewer, a PACKAGED prompt-library file (e.g. the ``plan-review-*`` pass +
    criterion prompts, which are not reviewer-catalog entries but ARE first-class
    workflow prompts — the criteria-library↔prompt-library wiring, story B2), or a user
    ``.rebar/prompts/<id>.md`` file. Stdlib-only."""
    if prompt_id in load_catalog():
        return True
    if prompt_id in _packaged_prompt_files():
        return True
    if repo_root:
        f = Path(repo_root) / ".rebar" / "prompts" / f"{prompt_id}.md"
        try:
            return f.is_file()
        except OSError:
            return False
    return False


def prompt_override_drift(repo_root=None) -> list[str]:
    """Findings for project prompt OVERRIDES that changed a built-in's ``outputs``
    contract (workflow authoring v2, story 4b2f).

    For each ``.rebar/prompts/<id>.md`` whose ``<id>`` is ALSO a built-in packaged
    prompt, compare the override's front-matter ``outputs`` to the built-in's. A
    CHANGED ``outputs`` contract on an override is BREAKING (downstream steps bind to
    the declared output contract), so it returns a finding string; an identical or
    absent ``outputs`` is clean. Best-effort: any read/parse trouble is swallowed (the
    linter must never crash on a malformed prompt — that is the prompt's own lint)."""
    if not repo_root:
        return []
    findings: list[str] = []
    packaged = _packaged_prompt_files()
    override_dir = Path(repo_root) / ".rebar" / "prompts"
    try:
        entries = sorted(override_dir.glob("*.md"))
    except OSError:
        return []
    for path in entries:
        stem = path.name[:-3]
        if "." in stem:  # a `<id>.<variant>.md` overlay, not a base prompt
            continue
        pid = stem.replace("_", "-")
        if pid not in packaged:
            continue  # an override with no built-in counterpart cannot drift
        try:
            override_meta, _ = parse_front_matter(path.read_text(encoding="utf-8"))
            builtin_raw = _catalog_dir().joinpath(packaged[pid]).read_text(encoding="utf-8")
            builtin_meta, _ = parse_front_matter(builtin_raw)
        except Exception:  # noqa: BLE001 - unreadable/malformed prompt is not this check's job
            continue
        if override_meta.get("outputs") != builtin_meta.get("outputs"):
            findings.append(
                f"prompt override .rebar/prompts/{path.name} changes the built-in "
                f"{pid!r} outputs contract (built-in {builtin_meta.get('outputs')!r} → "
                f"override {override_meta.get('outputs')!r}); a changed outputs contract "
                f"on an override is BREAKING for downstream steps"
            )
    return findings


def resolve_prompt(
    reviewer: Reviewer | Prompt,
    variables: dict,
    langfuse_cfg=None,
    *,
    repo_root=None,
    variant: str | None = None,
) -> tuple[str, dict]:
    """Resolve a reviewer's system prompt → ``(compiled_text, prompt_meta)`` (WS-F1/F2).

    GIT-CANONICAL: the text is the committed prompt file's body (a user
    ``.rebar/prompts/<id>.md`` override, else the packaged ``*.md``), with front-matter
    stripped and any ``variant`` overlay applied; **Langfuse is never consulted for
    the text** (read-replica only). Front-matter-declared ``required`` variables must
    be supplied (else PromptError), and rendering is strict on used vars. The returned
    ``prompt_meta`` carries the content hash + provenance + variant and is threaded
    into the trace (via RunRequest.langfuse_prompt), so the exact prompt bytes that
    ran are recorded and any divergence from a Langfuse copy is visible.

    ``langfuse_cfg`` is accepted for call-site compatibility but no longer drives a
    text fetch."""
    body, meta = load_prompt(reviewer, repo_root=repo_root, variant=variant)
    # Mirror prompt_input_schema's required/optional contract exactly: when
    # front-matter declares `variables`, an absent `required` key means ALL
    # declared vars are required, and any declared-but-not-required var is OPTIONAL
    # — it defaults to empty when omitted instead of failing strict rendering (a
    # declared-optional var must not be de-facto required). Undeclared used vars
    # still raise. No front-matter → the legacy strict path (every used var
    # required) is preserved for the review prompts.
    render_vars = dict(variables)
    if "variables" in meta:
        declared = list(meta.get("variables") or [])
        required = list(meta.get("required", declared))
        missing_required = sorted(set(required) & set(declared) - set(variables))
        if missing_required:
            raise PromptError(
                f"prompt {reviewer.id!r} requires variable(s) {missing_required} "
                "that were not supplied"
            )
        for v in declared:
            if v not in required:
                render_vars.setdefault(v, "")
    else:
        missing_required = sorted(set(meta.get("required") or []) - set(variables))
        if missing_required:
            raise PromptError(
                f"prompt {reviewer.id!r} requires variable(s) {missing_required} "
                "that were not supplied"
            )
    compiled = _render_strict(body, render_vars)
    return compiled, {
        "prompt_id": reviewer.id,
        "content_sha256": prompt_content_hash(body),
        "source": "git",
        "variant": variant,
    }


def _glob_match(path: str, pattern: str) -> bool:
    """Delegates to the single implementation in ``_engine_support.commit_impact``.

    The `**/`-at-repo-root rule is shared with the deterministic close gate, which cannot
    import this (optional ``[agents]``) package — so the rule lives there and this stays a
    thin wrapper to keep existing callers and monkeypatch targets working.
    """
    from rebar._engine_support.commit_impact import glob_match

    return glob_match(path, pattern)


def select_reviewers(
    changed_files: list[str], *, catalog: dict[str, Reviewer] | None = None
) -> list[str]:
    """Deterministic reviewer selection for a change (the rule layer used by the
    future code-review op). Returns the union of every ``default`` reviewer and
    every reviewer whose ``applies_to`` globs match a changed file, in catalog
    order. Pure + table-driven so it is fully offline-testable.
    """
    cat = catalog if catalog is not None else load_catalog()
    selected: list[str] = []
    for rid, rv in cat.items():
        if rv.default or any(_glob_match(f, g) for g in rv.applies_to for f in changed_files):
            selected.append(rid)
    return selected


def _main(argv: list[str] | None = None) -> int:
    """``python -m rebar.llm.prompting.prompts regenerate-index`` — regenerate the derived
    ``reviewers/index.json`` (the CI drift gate writes-then-diffs this)."""
    import sys

    args = list(sys.argv[1:] if argv is None else argv)
    cmd = args[0] if args else "regenerate-index"
    if cmd in ("regenerate-index", "regenerate_index"):
        regenerate_prompt_index()
        return 0
    sys.stderr.write(f"unknown command {cmd!r}; expected 'regenerate-index'\n")
    return 2


if __name__ == "__main__":
    raise SystemExit(_main())
