#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup-ci-service-account.sh — provision the rebar CI Gerrit service account that
# GitHub Actions authenticates as to cast the `Verified` label over SSH. Epic 1fa8 /
# story S4. Sibling of service-user.sh (the review-bot HTTP identity).
#
# Run from a workstation that holds the Gerrit ADMIN ssh key. This PoC runs
# DEVELOPMENT_BECOME_ANY_ACCOUNT, so cookie-auth REST mutations are refused — the CI
# account is created + configured via the Gerrit SSH admin command set (authenticated
# by the admin SSH key), NOT via REST.
#
# WHAT THIS DOES (and does NOT):
#   - Creates (or ensures) the CI service account and puts it in the "Service Users"
#     group, so the `label-Verified = … group Service Users` ACL in project.config
#     applies to it (developers can't self-cast Verified — see ADR-0020).
#   - Registers its SSH PUBLIC key so GitHub Actions (holding the matching PRIVATE
#     key as the GERRIT_SSH_PRIVKEY secret) can SSH in on :29418 to vote (ADR-0023).
#   - Does NOT touch any PRIVATE key or SSM. The keypair is generated by the operator
#     (see infra/runbooks/g2p-ci-credentials.md); the PRIVATE half goes to the GitHub
#     Actions secret + SSM /rebar/prod/ci-gerrit-ssh-key, and ONLY the PUBLIC half is
#     handed to this script. No secret value is ever read or echoed here.
#   - Does NOT create an HTTP password: the CI account's ONLY credential is its SSH
#     key (the vote path is `ssh -p 29418 … gerrit review`). Unlike the review-bot
#     (service-user.sh), it has no webhook/HTTP surface.
#
# Idempotent: re-running creates the account if absent, else ensures group membership
# and (re-)registers the public key. Adding an already-present key is treated as a
# no-op.
#
# Env:
#   GERRIT_HOST           (default rebar.solutions.navateam.com)
#   GERRIT_SSH_PORT       (default 29418)
#   GERRIT_SSH_USER       (default admin)          — the ADMIN account we run as
#   GERRIT_ADMIN_SSH_KEY  (default ~/.ssh/gerrit_admin)
#   CI_BOT_USER           (default rebar-ci-bot)   — the CI service account username
#   CI_BOT_EMAIL          (default rebar-ci-bot@rebar.solutions.navateam.com)
#   CI_SSH_PUBKEY_FILE    (default ~/.ssh/rebar_ci_gerrit.pub) — the PUBLIC key to
#                          register (NOT secret). The matching private key is the
#                          GitHub Actions GERRIT_SSH_PRIVKEY secret.
# ---------------------------------------------------------------------------
set -euo pipefail

GERRIT_HOST="${GERRIT_HOST:-rebar.solutions.navateam.com}"
GERRIT_SSH_PORT="${GERRIT_SSH_PORT:-29418}"
GERRIT_SSH_USER="${GERRIT_SSH_USER:-admin}"
GERRIT_ADMIN_SSH_KEY="${GERRIT_ADMIN_SSH_KEY:-$HOME/.ssh/gerrit_admin}"
CI_BOT_USER="${CI_BOT_USER:-rebar-ci-bot}"
CI_BOT_EMAIL="${CI_BOT_EMAIL:-rebar-ci-bot@rebar.solutions.navateam.com}"
CI_SSH_PUBKEY_FILE="${CI_SSH_PUBKEY_FILE:-$HOME/.ssh/rebar_ci_gerrit.pub}"

# --- 1. Fail-fast on missing inputs ----------------------------------------
[ -f "$GERRIT_ADMIN_SSH_KEY" ] || {
	echo "setup-ci-service-account: admin SSH key not found at $GERRIT_ADMIN_SSH_KEY" >&2
	exit 1
}
[ -f "$CI_SSH_PUBKEY_FILE" ] || {
	echo "setup-ci-service-account: CI public key not found at $CI_SSH_PUBKEY_FILE" >&2
	echo "  Generate the keypair first (see infra/runbooks/g2p-ci-credentials.md):" >&2
	echo "    ssh-keygen -t ed25519 -C rebar-ci-gerrit -f ~/.ssh/rebar_ci_gerrit -N ''" >&2
	exit 1
}

# Sanity: the file must LOOK like an OpenSSH public key (single line, ssh-*/ecdsa-*/
# sk-* prefix). This guards against accidentally handing this script a PRIVATE key.
pubkey="$(head -n1 "$CI_SSH_PUBKEY_FILE")"
case "$pubkey" in
	ssh-* | ecdsa-* | sk-ssh-* | sk-ecdsa-*) : ;;
	*)
		echo "setup-ci-service-account: ${CI_SSH_PUBKEY_FILE} does not look like an SSH PUBLIC key" >&2
		echo "  (expected a line starting with ssh-ed25519 / ssh-rsa / ecdsa-… ). Refusing." >&2
		echo "  Did you point CI_SSH_PUBKEY_FILE at the PRIVATE key by mistake?" >&2
		exit 1
		;;
esac
if grep -q 'PRIVATE KEY' "$CI_SSH_PUBKEY_FILE"; then
	echo "setup-ci-service-account: ${CI_SSH_PUBKEY_FILE} contains a PRIVATE KEY block — refusing." >&2
	exit 1
fi

SSH="ssh -i $GERRIT_ADMIN_SSH_KEY -p $GERRIT_SSH_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
GERRIT_SSH="$SSH ${GERRIT_SSH_USER}@${GERRIT_HOST}"

# --- 2. Idempotent account create ------------------------------------------
# Try to create the CI account in "Service Users" with its SSH public key. If the
# account already exists, create-account fails — fall through to set-account to ensure
# group membership + (re-)register the key. Either way the account ends up in Service
# Users with the given public key.
#
# The public key (which contains spaces) is piped on STDIN via `--ssh-key -`, so it is
# never mangled by Gerrit's SSH-command re-tokenizer (contrast the quoted-arg dance in
# service-user.sh). Args with spaces ("Service Users", full name) still need their
# inner quotes to survive transmission, so they carry an embedded \"...\" pair.
# Capture stderr so a REAL failure (bad key, unreachable host) is surfaced; only an
# "already exists" error should fall through. No secret is on any of these lines.
if err="$($GERRIT_SSH gerrit create-account "$CI_BOT_USER" \
	--group "\"Service Users\"" \
	--full-name "\"rebar CI bot\"" \
	--email "$CI_BOT_EMAIL" \
	--ssh-key - <"$CI_SSH_PUBKEY_FILE" 2>&1 1>/dev/null)"; then
	echo "setup-ci-service-account: created account '$CI_BOT_USER' in Service Users with its SSH key" >&2
else
	case "$err" in
		*"already exists"*|*"already used"*|*"exists"*) : ;;  # fall through to ensure state
		*) echo "setup-ci-service-account: create-account failed: $err" >&2; exit 1 ;;
	esac
	echo "setup-ci-service-account: account '$CI_BOT_USER' exists — ensuring group + key" >&2

	# Ensure "Service Users" membership (idempotent: re-adding an existing member is
	# benign). This is the ACL hook that grants label-Verified (project.config).
	$GERRIT_SSH gerrit set-members "\"Service Users\"" --add "$CI_BOT_USER"
	echo "setup-ci-service-account: ensured '$CI_BOT_USER' in Service Users" >&2

	# (Re-)register the public key. Adding a key that is already present makes Gerrit
	# error ("already"/"duplicate") — treat that as a no-op so re-runs are idempotent.
	if kerr="$($GERRIT_SSH gerrit set-account "$CI_BOT_USER" \
		--add-ssh-key - <"$CI_SSH_PUBKEY_FILE" 2>&1 1>/dev/null)"; then
		echo "setup-ci-service-account: registered SSH public key on '$CI_BOT_USER'" >&2
	else
		case "$kerr" in
			*"already"*|*"duplicate"*|*"exists"*) echo "setup-ci-service-account: SSH key already present (no-op)" >&2 ;;
			*) echo "setup-ci-service-account: add-ssh-key failed: $kerr" >&2; exit 1 ;;
		esac
	fi
fi

echo "setup-ci-service-account: DONE — CI service account '$CI_BOT_USER' ready to cast Verified over SSH" >&2
echo "  Next (operator): put the matching PRIVATE key in SSM /rebar/prod/ci-gerrit-ssh-key" >&2
echo "  and in the GitHub Actions secret GERRIT_SSH_PRIVKEY. See g2p-ci-credentials.md." >&2
