from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import NamedTuple

_CAP_PER_PASS = 5


def _default_repo_root() -> Path:
    """Repo root: REBAR_ROOT env if set, else the engine's parent.

    (Depth-math fallback only applies when no env is set; the rebar library/CLI
    always export REBAR_ROOT, and the reconciler threads --repo-root.)
    """
    root = os.environ.get("REBAR_ROOT")
    return Path(root) if root else Path(__file__).resolve().parents[4]


def _default_ticket_cli() -> str:
    """Path to the in-process rebar CLI (the ticket reader), self-resolved."""
    from rebar._engine import in_process_cli

    return in_process_cli()


# Canonical rebar ticket ID format: four groups of four lowercase hex
# digits separated by hyphens (e.g. "abc1-def2-1234-5678"). Generated by
# ticket-create.sh from a UUID4 prefix (see ticket-create.sh ~line 181).
# Anchored to word boundaries so we extract the ID even when it appears
# alongside other tokens ("Created ticket abc1-def2-1234-5678: title").
_TICKET_ID_RE = re.compile(r"\b[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}\b")


def _extract_ticket_id(stdout: str) -> str:
    """Extract a canonical rebar ticket ID from ticket-create.sh stdout.

    ticket-create.sh emits two lines on success:
        Created ticket <alias> (<id>): <title>      # human-readable
        <id>                                         # canonical, final line

    The canonical ID is the LAST occurrence of the 16-hex pattern in
    stdout — that matches the final line emitted by the script and is
    robust to alias prefixes, descriptive titles, or extra log lines
    that happen to contain hex tokens earlier in the output.

    Returns the empty string when no canonical-format ID is found
    (e.g. on garbage output like "ERROR" or a malformed CLI shim).
    Callers must treat an empty return value as "do not link" — patching
    an alert with a garbage ID is worse than leaving it orphan-with-warning.
    """
    matches = _TICKET_ID_RE.findall(stdout)
    return matches[-1] if matches else ""


def _load_alert_store():
    """Load the sibling alert_store.py module.

    No repo_root parameter — alert_store always lives next to this file in the
    rebar_reconciler package; accepting a configurable path would be misleading
    because the path is not actually used.
    """
    spec = importlib.util.spec_from_file_location(
        "alert_store", Path(__file__).parent / "alert_store.py"
    )
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("invariants_alert_store", mod)
    spec.loader.exec_module(mod)
    return mod


_SINK_MOD = None


def _load_sink():
    """Load the sibling invariant_sink.py module (the remediation side-effect sink).

    Mirrors ``_load_alert_store``'s by-path load (this module is exec'd standalone in
    tests, so a plain import would not resolve). The sink is stateless, so the loaded
    module is cached to avoid re-exec on every reconciler pass.
    """
    global _SINK_MOD
    if _SINK_MOD is None:
        spec = importlib.util.spec_from_file_location(
            "invariant_sink", Path(__file__).parent / "invariant_sink.py"
        )
        assert spec is not None and spec.loader is not None
        mod = importlib.util.module_from_spec(spec)
        sys.modules.setdefault("invariants_sink", mod)
        spec.loader.exec_module(mod)
        _SINK_MOD = mod
    return _SINK_MOD


class AtMostOneViolation(NamedTuple):
    """A structured at-most-one-local-id violation (a PURE detection record).

    Carries everything the remediation sink needs without any I/O: the offending
    ``jira_key``, its duplicate ``local_ids``, and the canonical + legacy dedup keys
    (the "bridge-alert:" namespace contract lives here, computed purely from the key).

    A NamedTuple (not a dataclass) deliberately: invariants.py is exec'd standalone in
    tests via ``spec_from_file_location`` WITHOUT registering the module in
    ``sys.modules``, and on Python 3.14 ``@dataclass`` resolves stringified
    (PEP 563) annotations through ``sys.modules[cls.__module__]`` at class-definition
    time, which raises ``AttributeError`` for such an unregistered module. NamedTuple
    does not, so it is robust to every load path.
    """

    jira_key: str
    local_ids: list
    dedup_key: str
    legacy_dedup_key: str


def detect_at_most_one_local_id(snapshot: dict) -> list[AtMostOneViolation]:
    """PURE detector: find Jira issues mapped to more than one local_id.

    No I/O, no subprocess, no alert-store access — this is compute-only and directly
    unit-testable. ``snapshot`` maps jira_key -> {fields}. Returns one
    ``AtMostOneViolation`` per offending issue, in snapshot iteration order. Dedup and
    the per-pass cap are filing policy and live in the sink, not here, so this returns
    ALL structural violations.
    """
    violations: list[AtMostOneViolation] = []
    for jira_key, fields in snapshot.items():
        rebar_ids = fields.get("local_ids", [])
        if isinstance(rebar_ids, list) and len(rebar_ids) > 1:
            # Dedup key uses the canonical "bridge-alert:" namespace prefix per the
            # at-most-one-invariant ticket's Considerations section. Without the
            # prefix, cross-invariant dedup scanners that filter by "bridge-alert:"
            # prefix would miss these entries.
            violations.append(
                AtMostOneViolation(
                    jira_key=jira_key,
                    local_ids=rebar_ids,
                    dedup_key=f"bridge-alert:at-most-one:{jira_key}",
                    legacy_dedup_key=f"at-most-one:{jira_key}",
                )
            )
    return violations


def check_at_most_one_local_id(
    snapshot: dict,
    repo_root: Path | None = None,
    ticket_cli: str | None = None,
) -> list[dict]:
    """Check that no Jira issue has more than one local_id mapping (detect -> sink).

    Thin composition preserved for the caller (run_differs): PURE detection via
    ``detect_at_most_one_local_id`` feeds the remediation sink
    (``invariant_sink.file_at_most_one_violations``), which owns the dedup gate, the
    per-pass cap, the alert-store append, and the ticket-CLI bug-filing.

    snapshot: dict mapping jira_key -> {fields}. Returns list of violation dicts filed
    this pass.

    Bug-filing failures (TimeoutExpired, FileNotFoundError, OSError) are surfaced to
    stderr but do NOT abort the loop or re-raise — the alert record itself is left in
    place so the next reconciler pass re-files cleanly instead of being short-circuited
    by is_deduped on an orphaned record. (``subprocess`` is passed into the sink from
    this module's namespace so the invariants tests that patch ``invariants.subprocess``
    still intercept the CLI call.)
    """
    if repo_root is None:
        repo_root = _default_repo_root()
    if ticket_cli is None:
        ticket_cli = _default_ticket_cli()

    violations = detect_at_most_one_local_id(snapshot)
    return _load_sink().file_at_most_one_violations(
        violations,
        repo_root=repo_root,
        ticket_cli=ticket_cli,
        alert_store=_load_alert_store(),
        runner=subprocess,
        extract_ticket_id=_extract_ticket_id,
        cap=_CAP_PER_PASS,
    )


# ---------------------------------------------------------------------------
# Story 7a75: dual-identity completeness verifier + schema-drift reporter
# ---------------------------------------------------------------------------

# Cap on quarantine entries reported per pass for the dual-identity verifier.
# Distinct from `_CAP_PER_PASS` above (which gates the at-most-one invariant);
# kept separate so the two invariants tune independently.
_DUAL_IDENTITY_CAP_PER_PASS = 50


# ``lazy_load`` centralizes the by-path sibling-loader idiom (rebar_reconciler/
# _loader.py). Import it normally when package context exists, else bootstrap it
# by file path — this module is itself exec'd standalone via
# spec_from_file_location in tests.
try:
    from rebar_reconciler._loader import lazy_load
except ImportError:  # standalone load without package context
    _loader_key = "rebar_reconciler._loader"
    if _loader_key not in sys.modules:
        _loader_spec = importlib.util.spec_from_file_location(
            _loader_key, Path(__file__).parent / "_loader.py"
        )
        assert _loader_spec is not None and _loader_spec.loader is not None
        _loader_mod = importlib.util.module_from_spec(_loader_spec)
        sys.modules[_loader_key] = _loader_mod
        _loader_spec.loader.exec_module(_loader_mod)  # type: ignore[union-attr]
    lazy_load = sys.modules[_loader_key].lazy_load


_MUTATION_KEY = "rebar_reconciler.mutation"


def _load_mutation_module():
    """Load mutation.py under the canonical dotted sys.modules key.

    Reuses ``rebar_reconciler.mutation`` so that ``Mutation``,
    ``MutationDirection``, and ``MutationAction`` share a single class identity
    across the reconciler — invariants.py, applier.py, differ.py, and any other
    callers compare against the SAME enum members. A previous version loaded
    under a private key (``invariants_mutation``), producing two distinct
    ``MutationDirection`` class objects so ``mutation.direction is X`` checks
    silently failed cross-module.
    """
    return lazy_load(_MUTATION_KEY, "mutation.py")


def check_dual_identity_complete(local_state: dict, jira_state: dict) -> tuple[set[str], list]:
    """Verify bidirectional binding between local tickets and Jira issues.

    For each local entry with a ``local_id``, find the Jira side whose
    ``local_id`` matches. Inconsistencies are classified as:

    * **Missing back-pointer** (local has no ``jira_key``) -> seed an inbound
      ``repair_property`` Mutation to write the back-pointer.
    * **Conflicting back-pointer** (local's ``jira_key`` does not match the
      matched peer) -> quarantine the local key.
    * **Double-bind** (more than one Jira issue claims the same
      ``local_id``) -> quarantine the local key and every colliding Jira
      key.

    Returns:
        (quarantine_keys, seed_repair_property_mutations)
    """
    mut_mod = _load_mutation_module()
    quarantine: set[str] = set()
    repairs: list = []

    jira_local_id_index: dict[str, list[str]] = {}
    for jk, jentry in jira_state.items():
        jid = jentry.get("local_id")
        if not jid:
            continue
        jira_local_id_index.setdefault(jid, []).append(jk)

    for local_key, local in local_state.items():
        rebar_id = local.get("local_id")
        if not rebar_id:
            continue
        peer_keys = jira_local_id_index.get(rebar_id, [])
        if not peer_keys:
            continue
        if len(peer_keys) > 1:
            quarantine.add(local_key)
            for jk in peer_keys:
                quarantine.add(jk)
            if len(quarantine) >= _DUAL_IDENTITY_CAP_PER_PASS:
                report_schema_drift(
                    local_key,
                    observed={},
                    expected={"invariants-cap-hit": True},
                )
                break
            continue
        peer_key = peer_keys[0]
        local_jira_pointer = local.get("jira_key")
        if local_jira_pointer and local_jira_pointer != peer_key:
            quarantine.add(local_key)
            continue
        if not local_jira_pointer:
            # Align the seeded mutation with applier.inbound_repair_property's
            # contract: target = JIRA issue key (peer_key), payload carries the
            # local_id used to write the local_id entity property. A prior
            # version emitted target=local_key + payload={set_field, value},
            # which did not match the leaf's expected schema and silently
            # short-circuited dispatch. (coderabbit / contract-shape fix)
            repairs.append(
                mut_mod.Mutation(
                    direction=mut_mod.MutationDirection.inbound,
                    action=mut_mod.MutationAction.repair_property,
                    target=peer_key,
                    payload={"local_id": rebar_id},
                    provenance={
                        "reason": "missing_back_pointer",
                        "local_key": local_key,
                        "peer": peer_key,
                    },
                )
            )

    return quarantine, repairs


def report_schema_drift(issue_key: str, observed: dict, expected: dict) -> None:
    """File a bug ticket for schema drift via the rebar dispatcher (thin sink wrapper).

    Delegates the side effects (dedup gate + alert-store append + best-effort ticket
    filing) to ``invariant_sink.report_schema_drift``. This wrapper resolves the
    collaborators from THIS module's namespace — ``subprocess`` and
    ``_load_alert_store`` — so the invariants tests that patch ``invariants.subprocess``
    / ``invariants._load_alert_store`` still intercept them, and passes the ticket-CLI
    resolver lazily so a deduped call does no extra work.

    Uses a stable ``dedup_key`` of the form ``bridge-alert:schema-drift:<issue_key>``
    so repeated drift on the same issue can be correlated. The dedup check prevents
    duplicate tickets across reconciler passes (root cause of bug
    1c59-90ca-3391-46ac: 12+ duplicate "schema drift: L-16" tickets from repeated
    cap-hit signals). Subprocess failures are swallowed (``check=False``) — drift
    reporting is best-effort and must not abort the reconcile loop.
    """
    _load_sink().report_schema_drift(
        issue_key,
        observed,
        expected,
        repo_root=_default_repo_root(),
        alert_store=_load_alert_store(),
        runner=subprocess,
        resolve_ticket_cli=_default_ticket_cli,
    )
