from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import sys
import time
from pathlib import Path

_CAP_PER_PASS = 5


def _default_repo_root() -> Path:
    """Repo root: REBAR_ROOT/PROJECT_ROOT env if set, else the engine's parent.

    (Depth-math fallback only applies when no env is set; the rebar library/CLI
    always export REBAR_ROOT, and the reconciler threads --repo-root.)
    """
    root = os.environ.get("REBAR_ROOT") or os.environ.get("PROJECT_ROOT")
    return Path(root) if root else Path(__file__).resolve().parents[4]


def _default_ticket_cli() -> str:
    """Path to the rebar dispatcher (the ticket CLI), one level above this pkg."""
    return os.environ.get("REBAR_TICKET_CLI") or str(
        Path(__file__).resolve().parent.parent / "rebar"
    )

# Canonical dso ticket ID format: four groups of four lowercase hex
# digits separated by hyphens (e.g. "abc1-def2-1234-5678"). Generated by
# ticket-create.sh from a UUID4 prefix (see ticket-create.sh ~line 181).
# Anchored to word boundaries so we extract the ID even when it appears
# alongside other tokens ("Created ticket abc1-def2-1234-5678: title").
_TICKET_ID_RE = re.compile(r"\b[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}\b")


def _extract_ticket_id(stdout: str) -> str:
    """Extract a canonical dso ticket ID from ticket-create.sh stdout.

    ticket-create.sh emits two lines on success:
        Created ticket <alias> (<id>): <title>      # human-readable
        <id>                                         # canonical, final line

    The canonical ID is the LAST occurrence of the 16-hex pattern in
    stdout — that matches the final line emitted by the script and is
    robust to alias prefixes, descriptive titles, or extra log lines
    that happen to contain hex tokens earlier in the output.

    Returns the empty string when no canonical-format ID is found
    (e.g. on garbage output like "ERROR" or a malformed CLI shim).
    Callers must treat an empty return value as "do not link" — patching
    an alert with a garbage ID is worse than leaving it orphan-with-warning.
    """
    matches = _TICKET_ID_RE.findall(stdout)
    return matches[-1] if matches else ""


def _load_alert_store():
    """Load the sibling alert_store.py module.

    No repo_root parameter — alert_store always lives next to this file in the
    rebar_reconciler package; accepting a configurable path would be misleading
    because the path is not actually used.
    """
    spec = importlib.util.spec_from_file_location(
        "alert_store", Path(__file__).parent / "alert_store.py"
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("invariants_alert_store", mod)
    spec.loader.exec_module(mod)
    return mod


def check_at_most_one_local_id(
    snapshot: dict,
    repo_root: Path | None = None,
    ticket_cli: str | None = None,
) -> list[dict]:
    """Check that no Jira issue has more than one local_id mapping.

    snapshot: dict mapping jira_key -> {fields}
    Returns list of violation dicts filed this pass.

    Bug-filing failures (TimeoutExpired, FileNotFoundError, OSError) are
    surfaced to stderr but do NOT abort the loop or re-raise — the alert
    record itself is rolled back so the next reconciler pass re-files cleanly
    instead of being short-circuited by is_deduped on an orphaned record.
    """
    if repo_root is None:
        repo_root = _default_repo_root()
    if ticket_cli is None:
        ticket_cli = _default_ticket_cli()

    alert_store = _load_alert_store()
    violations_filed = []

    for jira_key, fields in snapshot.items():
        # Check if this issue has multiple local_id values (duplicates)
        rebar_ids = fields.get("local_ids", [])
        if isinstance(rebar_ids, list) and len(rebar_ids) > 1:
            if len(violations_filed) >= _CAP_PER_PASS:
                continue

            # Dedup key uses the canonical "bridge-alert:" namespace prefix per
            # the at-most-one-invariant ticket's Considerations section. Without
            # the prefix, cross-invariant dedup scanners that filter by
            # "bridge-alert:" prefix would miss these entries.
            dedup_key = f"bridge-alert:at-most-one:{jira_key}"
            # Backward-compat: also check the legacy (pre-prefix) dedup_key so
            # alerts filed under the old format are recognized during the
            # transition window and not re-filed as duplicates.
            _legacy_dedup_key = f"at-most-one:{jira_key}"
            if alert_store.is_deduped(dedup_key, repo_root) or alert_store.is_deduped(
                _legacy_dedup_key, repo_root
            ):
                continue

            # File bridge-alert record
            record = {
                "key": dedup_key,
                "jira_key": jira_key,
                "timestamp_ns": time.time_ns(),
                "reason": f"multiple local_ids: {rebar_ids}",
            }
            alert_store.append(record, repo_root)

            # File bug ticket via CLI. Narrow exception handling: catch the
            # subprocess-class and OS-class exceptions explicitly so genuine
            # programming errors (AttributeError, TypeError) still propagate.
            bug_id = ""
            cli_error: str | None = None
            try:
                result = subprocess.run(
                    [
                        ticket_cli,
                        "create",
                        "bug",
                        f"at-most-one violation: {jira_key} has multiple local_ids",
                        "--priority",
                        "1",
                    ],
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                if result.returncode == 0 and result.stdout.strip():
                    bug_id = _extract_ticket_id(result.stdout)
                    if not bug_id:
                        # CLI exited 0 but stdout did not contain a
                        # canonical ticket ID — treat as failure so the
                        # alert remains orphan-with-warning instead of
                        # being patched with a garbage value.
                        cli_error = (
                            "exit=0 but no canonical ticket ID found in "
                            f"stdout={result.stdout[:200]!r}"
                        )
                else:
                    cli_error = (
                        f"exit={result.returncode} stderr={result.stderr[:200]!r}"
                    )
            except subprocess.TimeoutExpired:
                cli_error = "ticket-create timed out after 30s"
            except (OSError, subprocess.SubprocessError) as exc:
                cli_error = f"{type(exc).__name__}: {exc}"

            if bug_id:
                alert_store.patch_bug_filed(dedup_key, bug_id, repo_root)
            else:
                # Bug-filing failed. Surface the failure to operators via
                # stderr, then leave the alert record on disk. The next pass
                # will hit is_deduped() and skip — operators must manually
                # file the bug or roll the alert forward. See bug ticket TBD
                # for a sweeper that converts orphan alerts into ticket-create
                # retries on subsequent passes.
                print(  # noqa: T201
                    f"WARN: invariants.check_at_most_one_local_id: "
                    f"alert {dedup_key!r} filed but bug-ticket creation "
                    f"failed ({cli_error}); alert is orphan-without-bug.",
                    file=sys.stderr,
                )

            violations_filed.append(
                {
                    "jira_key": jira_key,
                    "local_ids": rebar_ids,
                    "dedup_key": dedup_key,
                }
            )

    return violations_filed


# ---------------------------------------------------------------------------
# Story 7a75: dual-identity completeness verifier + schema-drift reporter
# ---------------------------------------------------------------------------

# Cap on quarantine entries reported per pass for the dual-identity verifier.
# Distinct from `_CAP_PER_PASS` above (which gates the at-most-one invariant);
# kept separate so the two invariants tune independently.
_DUAL_IDENTITY_CAP_PER_PASS = 50


_MUTATION_KEY = "rebar_reconciler.mutation"


def _load_mutation_module():
    """Load mutation.py under the canonical dotted sys.modules key.

    Reuses ``rebar_reconciler.mutation`` so that ``Mutation``,
    ``MutationDirection``, and ``MutationAction`` share a single class identity
    across the reconciler — invariants.py, applier.py, differ.py, and any other
    callers compare against the SAME enum members. A previous version loaded
    under a private key (``invariants_mutation``), producing two distinct
    ``MutationDirection`` class objects so ``mutation.direction is X`` checks
    silently failed cross-module.
    """
    if _MUTATION_KEY in sys.modules:
        return sys.modules[_MUTATION_KEY]
    spec = importlib.util.spec_from_file_location(
        _MUTATION_KEY, Path(__file__).parent / "mutation.py"
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules[_MUTATION_KEY] = mod
    spec.loader.exec_module(mod)
    return mod


def check_dual_identity_complete(
    local_state: dict, jira_state: dict
) -> tuple[set[str], list]:
    """Verify bidirectional binding between local tickets and Jira issues.

    For each local entry with a ``local_id``, find the Jira side whose
    ``local_id`` matches. Inconsistencies are classified as:

    * **Missing back-pointer** (local has no ``jira_key``) -> seed an inbound
      ``repair_property`` Mutation to write the back-pointer.
    * **Conflicting back-pointer** (local's ``jira_key`` does not match the
      matched peer) -> quarantine the local key.
    * **Double-bind** (more than one Jira issue claims the same
      ``local_id``) -> quarantine the local key and every colliding Jira
      key.

    Returns:
        (quarantine_keys, seed_repair_property_mutations)
    """
    mut_mod = _load_mutation_module()
    quarantine: set[str] = set()
    repairs: list = []

    jira_local_id_index: dict[str, list[str]] = {}
    for jk, jentry in jira_state.items():
        jid = jentry.get("local_id")
        if not jid:
            continue
        jira_local_id_index.setdefault(jid, []).append(jk)

    for local_key, local in local_state.items():
        rebar_id = local.get("local_id")
        if not rebar_id:
            continue
        peer_keys = jira_local_id_index.get(rebar_id, [])
        if not peer_keys:
            continue
        if len(peer_keys) > 1:
            quarantine.add(local_key)
            for jk in peer_keys:
                quarantine.add(jk)
            if len(quarantine) >= _DUAL_IDENTITY_CAP_PER_PASS:
                report_schema_drift(
                    local_key,
                    observed={},
                    expected={"invariants-cap-hit": True},
                )
                break
            continue
        peer_key = peer_keys[0]
        local_jira_pointer = local.get("jira_key")
        if local_jira_pointer and local_jira_pointer != peer_key:
            quarantine.add(local_key)
            continue
        if not local_jira_pointer:
            # Align the seeded mutation with applier.inbound_repair_property's
            # contract: target = JIRA issue key (peer_key), payload carries the
            # local_id used to write the local_id entity property. A prior
            # version emitted target=local_key + payload={set_field, value},
            # which did not match the leaf's expected schema and silently
            # short-circuited dispatch. (coderabbit / contract-shape fix)
            repairs.append(
                mut_mod.Mutation(
                    direction=mut_mod.MutationDirection.inbound,
                    action=mut_mod.MutationAction.repair_property,
                    target=peer_key,
                    payload={"local_id": rebar_id},
                    provenance={
                        "reason": "missing_back_pointer",
                        "local_key": local_key,
                        "peer": peer_key,
                    },
                )
            )

    return quarantine, repairs


def report_schema_drift(issue_key: str, observed: dict, expected: dict) -> None:
    """File a bug ticket for schema drift via the rebar dispatcher.

    Uses a stable ``dedup_key`` of the form ``bridge-alert:schema-drift:<issue_key>``
    so repeated drift on the same issue can be correlated.  The alert_store
    dedup check prevents duplicate tickets across reconciler passes — without
    it, every pass that hits the cap fires a new ticket for the same key
    (root cause of bug 1c59-90ca-3391-46ac: 12+ duplicate "schema drift: L-16"
    tickets created by repeated cap-hit signals).

    Subprocess failures are swallowed (``check=False``) — drift reporting is
    best-effort and must not abort the reconcile loop.

    NOTE: The previous implementation used ``python -m reconciler_cli`` which
    does not exist as a module in this repo.  This version uses the same
    ``rebar create`` dispatcher as the rest of invariants.py.
    """
    dedup_key = f"bridge-alert:schema-drift:{issue_key}"
    repo_root = _default_repo_root()

    alert_store = _load_alert_store()
    if alert_store.is_deduped(dedup_key, repo_root):
        return

    # Persist the alert record before filing the ticket so subsequent passes
    # hit is_deduped() and skip, mirroring the pattern in
    # check_at_most_one_local_id().
    alert_store.append(
        {
            "key": dedup_key,
            "issue_key": issue_key,
            "timestamp_ns": time.time_ns(),
            "reason": f"schema-drift observed={observed} expected={expected}",
        },
        repo_root,
    )

    ticket_cli = _default_ticket_cli()
    subprocess.run(
        [
            ticket_cli,
            "create",
            "bug",
            f"schema drift: {issue_key}",
            "--priority",
            "2",
            "--description",
            f"dedup_key={dedup_key} observed={observed} expected={expected}",
        ],
        check=False,
    )
