#!/usr/bin/env python3
"""Cast the Gerrit Verified vote from the GitHub Actions gate result."""

from __future__ import annotations

import os
import shlex
import subprocess
import sys
from pathlib import Path

_VOTE_TYPES = {
    "success": ("SUCCESS", ("--label", "Verified=1")),
    "failure": ("FAILURE", ("--label", "Verified=-1")),
    "cancelled": ("CANCELLED", ("--label", "Verified=-1", "--label", "Code-Review=-1")),
}
_CLOSED_CHANGE_NEEDLE = "fatal: change is closed"


def _error(message: str) -> None:
    print(f"::error::{message}", file=sys.stderr)


def _require_env(name: str) -> str:
    value = os.environ.get(name, "")
    if not value:
        raise ValueError(f"{name} is required")
    return value


def _positive_integer(value: str, name: str) -> str:
    if not value.isdecimal() or value.startswith("0"):
        raise ValueError(f"{name} must be a positive integer")
    return value


def _install_ssh_material(home: Path, private_key: str, known_hosts: str) -> tuple[Path, Path]:
    ssh_dir = home / ".ssh"
    ssh_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    key_path = ssh_dir / "gerrit_verified_key"
    key_path.write_text(private_key.rstrip("\n") + "\n", encoding="utf-8")
    key_path.chmod(0o600)
    known_hosts_path = ssh_dir / "gerrit_verified_known_hosts"
    known_hosts_path.write_text(known_hosts.rstrip("\n") + "\n", encoding="utf-8")
    known_hosts_path.chmod(0o600)
    return key_path, known_hosts_path


def _is_closed_change_error(completed: subprocess.CompletedProcess[str]) -> bool:
    return _CLOSED_CHANGE_NEEDLE in f"{completed.stderr}\n{completed.stdout}"


def _remote_command(change: str, patchset: str, message: str, labels: tuple[str, ...]) -> str:
    args = [
        "gerrit",
        "review",
        f"{change},{patchset}",
        "--message",
        message,
        *labels,
        "--tag",
        "autogenerated:github",
    ]
    return " ".join(shlex.quote(arg) for arg in args)


def main() -> int:
    try:
        vote_type = _require_env("VOTE_TYPE")
        if vote_type not in _VOTE_TYPES:
            raise ValueError(
                f"Unknown vote type {vote_type!r}: expected success, failure or cancelled"
            )
        change = _positive_integer(_require_env("CHANGE_NUMBER"), "CHANGE_NUMBER")
        patchset = _positive_integer(_require_env("PATCHSET_NUMBER"), "PATCHSET_NUMBER")
        server = _require_env("GERRIT_SERVER")
        user = _require_env("GERRIT_SSH_USER")
        private_key = _require_env("GERRIT_SSH_PRIVKEY")
        known_hosts = _require_env("GERRIT_KNOWN_HOSTS")
        run_url = _require_env("RUN_URL")
    except ValueError as exc:
        _error(str(exc))
        return 1

    status, labels = _VOTE_TYPES[vote_type]
    key_path, known_hosts_path = _install_ssh_material(Path.home(), private_key, known_hosts)
    message = f"{status}: {run_url}"
    command = [
        "ssh",
        "-i",
        str(key_path),
        "-p",
        "29418",
        "-o",
        "StrictHostKeyChecking=yes",
        "-o",
        f"UserKnownHostsFile={known_hosts_path}",
        "--",
        f"{user}@{server}",
        _remote_command(change, patchset, message, labels),
    ]
    try:
        completed = subprocess.run(command, text=True, capture_output=True, check=False)
    finally:
        key_path.unlink(missing_ok=True)
        known_hosts_path.unlink(missing_ok=True)
    if completed.stdout:
        print(completed.stdout, end="")
    if completed.stderr:
        print(completed.stderr, end="", file=sys.stderr)
    if completed.returncode != 0 and _is_closed_change_error(completed):
        print(
            "::notice::Gerrit change is already closed "
            f"({change},{patchset}); treating the Verified "
            f"{vote_type} vote as a benign no-op."
        )
        return 0
    return completed.returncode


if __name__ == "__main__":
    sys.exit(main())
