#!/usr/bin/env python3
"""Generate the ticket type/status taxonomy in ``docs/ticket-model.md``.

``src/rebar/types.py`` owns the canonical ``TicketType`` and ``TicketStatus`` Literal
vocabularies. This script renders the marked documentation block from those Literals so
the docs do not hand-maintain counts or member lists.

Usage:
    python scripts/gen_ticket_model_taxonomy.py
    python scripts/gen_ticket_model_taxonomy.py --check
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path
from typing import get_args

REPO_ROOT = Path(__file__).resolve().parents[1]
DOC = REPO_ROOT / "docs" / "ticket-model.md"
TYPES = REPO_ROOT / "src" / "rebar" / "types.py"

BEGIN_MARKER = "<!-- BEGIN GENERATED TICKET TAXONOMY -->"
END_MARKER = "<!-- END GENERATED TICKET TAXONOMY -->"

_LEGACY_TAXONOMY_RE = re.compile(
    r"^A ticket is one of .*?\n\n(?=## The `idea` status)",
    flags=re.MULTILINE | re.DOTALL,
)


def _load_types(types_path: Path) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Load canonical ticket vocabularies from ``types_path`` in Literal order."""
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec = importlib.util.spec_from_file_location("_rebar_ticket_taxonomy_types", types_path)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"cannot load types module from {types_path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    finally:
        sys.dont_write_bytecode = previous_dont_write_bytecode

    try:
        ticket_types = tuple(str(value) for value in get_args(module.TicketType))
        ticket_statuses = tuple(str(value) for value in get_args(module.TicketStatus))
    except AttributeError as exc:
        raise RuntimeError(f"{types_path} must define TicketType and TicketStatus") from exc
    if not ticket_types or not ticket_statuses:
        raise RuntimeError(f"{types_path} TicketType and TicketStatus must be non-empty Literals")
    return ticket_types, ticket_statuses


def _markdown_table(values: tuple[str, ...]) -> str:
    rows = ["| value |", "| --- |"]
    rows.extend(f"| `{value}` |" for value in values)
    return "\n".join(rows)


def _render_block(ticket_types: tuple[str, ...], ticket_statuses: tuple[str, ...]) -> str:
    return (
        f"{BEGIN_MARKER}\n"
        "<!-- Generated by scripts/gen_ticket_model_taxonomy.py; do not edit by hand. -->\n"
        "## Ticket type and status taxonomy\n"
        "\n"
        "The canonical ticket vocabulary is generated from `src/rebar/types.py`.\n"
        "\n"
        f"There are {len(ticket_types)} canonical ticket types, in declaration order:\n"
        "\n"
        f"{_markdown_table(ticket_types)}\n"
        "\n"
        f"There are {len(ticket_statuses)} canonical ticket statuses, in declaration order:\n"
        "\n"
        f"{_markdown_table(ticket_statuses)}\n"
        f"{END_MARKER}\n"
    )


def _replace_generated_block(document: str, generated_block: str) -> str:
    begin_count = document.count(BEGIN_MARKER)
    end_count = document.count(END_MARKER)
    if begin_count != end_count:
        raise RuntimeError("ticket taxonomy markers are unbalanced")
    if begin_count > 1:
        raise RuntimeError("ticket taxonomy markers appear more than once")
    if begin_count == 1:
        begin = document.index(BEGIN_MARKER)
        end = document.index(END_MARKER) + len(END_MARKER)
        if end < len(document) and document[end] == "\n":
            end += 1
        return document[:begin] + generated_block + document[end:]

    replaced, replacements = _LEGACY_TAXONOMY_RE.subn(generated_block + "\n", document, count=1)
    if replacements == 1:
        return replaced

    idea_heading = "## The `idea` status"
    if idea_heading not in document:
        raise RuntimeError("cannot place ticket taxonomy block: missing idea-status heading")
    return document.replace(idea_heading, generated_block + "\n" + idea_heading, 1)


def outside_generated_taxonomy(document: str) -> tuple[str, str]:
    """Return the document text before and after the generated taxonomy block."""
    begin = document.index(BEGIN_MARKER)
    end = document.index(END_MARKER) + len(END_MARKER)
    if end < len(document) and document[end] == "\n":
        end += 1
    return document[:begin], document[end:]


def _expected_document(doc_path: Path, types_path: Path) -> str:
    ticket_types, ticket_statuses = _load_types(types_path)
    document = doc_path.read_text(encoding="utf-8")
    return _replace_generated_block(document, _render_block(ticket_types, ticket_statuses))


def _check(doc_path: Path, types_path: Path) -> int:
    current = doc_path.read_text(encoding="utf-8")
    expected = _expected_document(doc_path, types_path)
    if current != expected:
        sys.stderr.write(
            f"ticket taxonomy is stale in {doc_path}; regenerate with "
            "`python scripts/gen_ticket_model_taxonomy.py`\n\n"
            f"Expected generated taxonomy:\n{_render_block(*_load_types(types_path))}"
        )
        return 1
    return 0


def _write(doc_path: Path, types_path: Path) -> int:
    expected = _expected_document(doc_path, types_path)
    doc_path.write_text(expected, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the ticket type/status taxonomy in docs/ticket-model.md."
    )
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if the taxonomy block drifts"
    )
    parser.add_argument("--doc", type=Path, default=DOC, help=argparse.SUPPRESS)
    parser.add_argument("--types", type=Path, default=TYPES, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    try:
        return _check(args.doc, args.types) if args.check else _write(args.doc, args.types)
    except RuntimeError as exc:
        sys.stderr.write(f"{exc}\n")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
