#!/usr/bin/env python3
"""Generate ``docs/config-reference.md`` and ``docs/security.md`` (ticket 3199, RP-04 S7.4).

Two NEW, fully-generated docs derived from rebar's typed config registries — modelled on
``scripts/gen_env_registry.py`` and ``scripts/gen_cli_reference.py``. The hand-authored
``docs/config.md`` is left ENTIRELY untouched; these are machine-current companions:

  * ``docs/config-reference.md`` — the configuration precedence / source / lifecycle
    reference. Every ``section.field`` row is derived from the typed config schema
    (``rebar._config_schema._SECTION_CLASSES``) with a LIFECYCLE annotation derived from
    the cfg-kind entries of ``rebar._deprecations.REGISTRY`` (deprecated aliases) and
    ``rebar._deprecations.tombstones()`` (removed keys).
  * ``docs/security.md`` — the indexed security reference, whose secret-name inventory is
    derived from ``rebar._child_env._ADAPTER_SECRET_NAMES``.

Registry-derivable rows are generated per-run; narrative topics that are not
registry-derivable (precedence, rotation, the observability exception, subprocess limits,
…) are emitted VERBATIM from the curated ``*_NARRATIVE`` constants below.

Usage:
    python scripts/gen_config_reference.py            # regenerate both docs
    python scripts/gen_config_reference.py --check     # exit non-zero if either is stale
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_REFERENCE_PATH = REPO_ROOT / "docs" / "config-reference.md"
SECURITY_PATH = REPO_ROOT / "docs" / "security.md"
GEN_CMD = "python scripts/gen_config_reference.py"

_BANNER = (
    f"**Generated by `{GEN_CMD}` — do not edit by hand.** Run "
    f"`{GEN_CMD}` to regenerate; a drift test (run under `make test`, no CI "
    "provider required) fails if this file is stale. The hand-authored `docs/config.md` "
    "remains the design-of-record "
    "narrative and is NOT touched by this generator."
)

# ── Curated narrative (config-reference.md) — NOT registry-derivable ─────────────
# Emitted verbatim; covers topic markers: precedence, source, lifecycle, rotation,
# native refresh, exposure.
_CONFIG_NARRATIVE = """\
## Precedence and source

rebar resolves every configuration key by layering sources highest-wins. The
**precedence** order, from strongest to weakest, is:

1. **CLI flags** — an explicit flag on the invoked command.
2. **Environment variables** — the `REBAR_<SECTION>_<KEY>` projection (see
   `docs/env-vars.md` for the enumerated registry) and the honored legacy aliases.
3. **Project config** — `rebar.toml` (or `[tool.rebar]` in `pyproject.toml`) in the
   working tree.
4. **User config** — the per-user config file discovered outside the project.
5. **Built-in defaults** — the dataclass defaults shown in the key table below.

Each resolved key therefore has a **source**: the highest-precedence layer that set it.
A key absent from every layer takes its built-in default, whose value is the `Default`
column below. This doc is the machine-current projection of the typed schema; the
prose design-of-record for each key lives in `docs/config.md`.

## Lifecycle

A configuration key moves through a **lifecycle**: *active* keys are the current,
supported surface (the table below). A key can then become a **deprecated alias** — the
old spelling is still honored (with a runtime warning) but resolves to a canonical
replacement — and finally a **removed key** (a tombstone): the old spelling no longer
does anything, and setting it either warns or fails loud depending on whether it was
operationally load-bearing. The two sections after the key table enumerate the current
deprecated aliases and removed keys derived from `rebar._deprecations`.

## Rotation, native refresh, and exposure

- **Rotation.** Configuration values (including any secret pulled from the environment)
  are read at process start. Rotating a value — a restart/redeploy rotation — means
  updating the source layer and **restarting the rebar process** (CLI invocation, MCP
  server, or reconciler) so the new value is read; rebar does not watch config files or
  environment for in-place changes.
- **Native refresh.** rebar performs no native refresh of live values: there is no
  background reloader that re-reads `rebar.toml` or the environment mid-run. A long-lived
  server picks up a changed key only on its next start.
- **Exposure (MCP/CLI exposure).** The resolved, non-secret configuration is exposed
  read-only through the `rebar config` CLI view and the MCP config-transparency surface.
  Secret **values** are never part of that exposure — only their presence/source — so a
  config dump is safe to share; see `docs/security.md` for the secret-name inventory.
"""

# ── Curated narrative (security.md) — NOT registry-derivable ─────────────────────
# Emitted verbatim; covers topic markers: observability, subprocess, behavior delta.
_SECURITY_NARRATIVE = """\
## Secret handling

rebar treats send credentials as **names, never values**. The adapter secret inventory
below is a registry of the exact environment-variable *names* each Jira adapter's send
credential lives under — it carries no secret material, so it is safe to commit, log, and
diff. Non-secret Jira configuration (`JIRA_URL` / `JIRA_USER` / `JIRA_PROJECT`) is
deliberately absent: only the sending-secret names are tracked and stripped.

## Child-process environment projection

When rebar spawns a child process it projects the parent environment through
`rebar._child_env.project_child_env`. An *owning* or *unrelated* child has every
adapter-owned secret NAME stripped from its inherited environment, so a child with no
business sending as an adapter cannot inherit that adapter's credential from the ambient
environment; an owning child receives its own credential only from an explicit overlay.

- **Observability exception.** The projection strips send-credential names but does not
  strip non-secret native variables — including the proxy, CA-bundle, and observability
  variables (tracing/telemetry endpoints) a child needs to emit spans and logs. This is a
  deliberate observability exception: dropping them would blind the child, and they carry
  no send capability.
- **Subprocess limitations.** The projection is a pure mapping transform over the base
  environment it is handed; it is not a sandbox. It governs only which environment
  variable NAMES a subprocess sees — it does not constrain the subprocess's filesystem,
  network, or process capabilities. Isolating those is the caller's responsibility.
- **Behavior delta.** Relative to inheriting the full ambient environment, the security
  behavior delta is precisely the removal of the adapter-owned secret names for a
  non-`same_capability` child (and the refusal to apply an overlay for an `unrelated`
  child). Every other variable — non-secret config and unknown native variables — passes
  through unchanged.
"""


def _load_registries() -> None:
    """Put ``src`` on ``sys.path`` so ``rebar.*`` imports resolve from this checkout."""
    src = str(REPO_ROOT / "src")
    if src not in sys.path:
        sys.path.insert(0, src)


def _field_default_repr(f: dataclasses.Field) -> str:
    """A stable literal representation of a dataclass field's default."""
    if f.default is not dataclasses.MISSING:
        return repr(f.default)
    if f.default_factory is not dataclasses.MISSING:
        return repr(f.default_factory())
    return "—"


def _field_type_repr(f: dataclasses.Field) -> str:
    """The field's annotation as text (``from __future__ import annotations`` → str)."""
    return f.type if isinstance(f.type, str) else getattr(f.type, "__name__", str(f.type))


def _cfg_deprecations() -> list[tuple[str, str, str]]:
    """(name, replacement, status) for each ``kind == 'cfg'`` deprecated alias."""
    from rebar._deprecations import REGISTRY

    rows: list[tuple[str, str, str]] = []
    for dep in REGISTRY.values():
        if dep.kind != "cfg":
            continue
        status = "permanent alias" if dep.permanent else f"deprecated (removal in {dep.remove_in})"
        rows.append((dep.name, dep.replacement, status))
    return sorted(rows)


def _cfg_tombstones() -> list[tuple[str, str, str]]:
    """(name, replacement, behavior) for each ``kind == 'cfg'`` removed key."""
    from rebar._deprecations import tombstones

    rows: list[tuple[str, str, str]] = []
    for ri in tombstones():
        if ri.kind != "cfg":
            continue
        rows.append((ri.name, ri.replacement, ri.behavior))
    return sorted(rows)


def _lifecycle_index() -> dict[str, str]:
    """Map a canonical schema key to a LIFECYCLE note when it supersedes an old spelling."""
    index: dict[str, str] = {}
    for name, replacement, status in _cfg_deprecations():
        if replacement:
            index.setdefault(replacement, f"active — supersedes alias `{name}` ({status})")
    for name, replacement, _behavior in _cfg_tombstones():
        if replacement:
            index.setdefault(replacement, f"active — replaces removed key `{name}`")
    return index


def _schema_rows() -> list[tuple[str, str, str, str]]:
    """(key, type, default, lifecycle) for every ``section.field`` in the typed schema."""
    from rebar._config_schema import _SECTION_CLASSES

    lifecycle = _lifecycle_index()
    rows: list[tuple[str, str, str, str]] = []
    for section, cls in _SECTION_CLASSES.items():
        for f in dataclasses.fields(cls):
            key = f"{section}.{f.name}"
            rows.append(
                (
                    key,
                    _field_type_repr(f),
                    _field_default_repr(f),
                    lifecycle.get(key, "active"),
                )
            )
    return rows


def _md_cell(text: str) -> str:
    """Escape a value for a single Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def render_config_reference() -> str:
    """Return the full markdown for ``docs/config-reference.md``."""
    _load_registries()
    rows = _schema_rows()
    deprecations = _cfg_deprecations()
    tomb = _cfg_tombstones()

    lines: list[str] = ["# Configuration reference", "", _BANNER, ""]
    lines.append(
        "The machine-current projection of rebar's typed configuration schema "
        "(`rebar._config_schema`). For the design-of-record narrative behind each key, "
        "read the hand-authored `docs/config.md`."
    )
    lines.append("")
    lines.append(_CONFIG_NARRATIVE.rstrip("\n"))
    lines.append("")
    lines.append("## Configuration keys")
    lines.append("")
    lines.append(f"The {len(rows)} typed `section.field` keys, with type, default, and lifecycle:")
    lines.append("")
    lines.append("| Key | Type | Default | Lifecycle |")
    lines.append("|-----|------|---------|-----------|")
    for key, type_repr, default_repr, lifecycle in rows:
        lines.append(
            f"| `{key}` | `{_md_cell(type_repr)}` | `{_md_cell(default_repr)}` "
            f"| {_md_cell(lifecycle)} |"
        )
    lines.append("")

    lines.append("## Deprecated configuration aliases")
    lines.append("")
    if deprecations:
        lines.append(
            "Old spellings still honored (with a runtime warning) that resolve to a "
            "canonical replacement — derived from the `cfg`-kind entries of "
            "`rebar._deprecations.REGISTRY`:"
        )
        lines.append("")
        lines.append("| Deprecated key | Replacement | Status |")
        lines.append("|----------------|-------------|--------|")
        for name, replacement, status in deprecations:
            repl = f"`{replacement}`" if replacement else "_(none)_"
            lines.append(f"| `{name}` | {repl} | {_md_cell(status)} |")
    else:
        lines.append("_None._")
    lines.append("")

    lines.append("## Removed configuration keys")
    lines.append("")
    if tomb:
        lines.append(
            "Fully-removed keys (tombstones): setting one no longer has any effect and is "
            "either warned or failed-loud — derived from the `cfg`-kind entries of "
            "`rebar._deprecations.tombstones()`:"
        )
        lines.append("")
        lines.append("| Removed key | Replacement | Behavior when still set |")
        lines.append("|-------------|-------------|-------------------------|")
        for name, replacement, behavior in tomb:
            repl = f"`{replacement}`" if replacement else "_(no replacement)_"
            lines.append(f"| `{name}` | {repl} | {_md_cell(behavior)} |")
    else:
        lines.append("_None._")
    lines.append("")

    return "\n".join(lines)


def _adapter_secret_rows() -> list[tuple[str, str]]:
    """(adapter, secret-name) rows from the adapter-secret registry, one row per name."""
    from rebar._child_env import _ADAPTER_SECRET_NAMES

    rows: list[tuple[str, str]] = []
    for adapter, names in _ADAPTER_SECRET_NAMES.items():
        for name in sorted(names):
            rows.append((adapter, name))
    return sorted(rows)


def render_security() -> str:
    """Return the full markdown for ``docs/security.md``."""
    _load_registries()
    from rebar._child_env import owned_secret_names

    rows = _adapter_secret_rows()
    union = sorted(owned_secret_names())

    lines: list[str] = ["# Security reference", "", _BANNER, ""]
    lines.append(
        "The machine-current index of rebar's security-relevant surface: the adapter "
        "send-credential name inventory (derived from "
        "`rebar._child_env._ADAPTER_SECRET_NAMES`) and the child-process environment "
        "projection contract."
    )
    lines.append("")
    lines.append(_SECURITY_NARRATIVE.rstrip("\n"))
    lines.append("")
    lines.append("## Adapter send-credential inventory")
    lines.append("")
    lines.append(f"The {len(union)} secret env-var NAME(s) rebar's Jira adapters own, by adapter:")
    lines.append("")
    lines.append("| Adapter | Secret env-var name |")
    lines.append("|---------|---------------------|")
    for adapter, name in rows:
        lines.append(f"| `{adapter}` | `{name}` |")
    lines.append("")
    lines.append(
        "Union of all owned secret names (`rebar._child_env.owned_secret_names()`): "
        + ", ".join(f"`{name}`" for name in union)
        + "."
    )
    lines.append("")

    return "\n".join(lines)


def _is_stale(path: Path, generated: str) -> bool:
    """True when the committed file differs from ``generated`` (newline-normalized)."""
    if not path.exists():
        return True
    current = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    return current != generated.replace("\r\n", "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the configuration and security reference docs."
    )
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if either committed doc is stale"
    )
    args = parser.parse_args(argv)

    config_doc = render_config_reference()
    security_doc = render_security()

    if args.check:
        stale = False
        for path, generated in (
            (CONFIG_REFERENCE_PATH, config_doc),
            (SECURITY_PATH, security_doc),
        ):
            if _is_stale(path, generated):
                try:
                    label = path.relative_to(REPO_ROOT)
                except ValueError:
                    label = path
                sys.stderr.write(f"{label} is stale — regenerate with `{GEN_CMD}`\n")
                stale = True
        return 1 if stale else 0

    CONFIG_REFERENCE_PATH.write_text(config_doc, encoding="utf-8")
    SECURITY_PATH.write_text(security_doc, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
