#!/usr/bin/env python3
"""Generate the canonical config-surface golden inventory.

This golden is the machine-current inventory of rebar's CANONICAL config surface:
every live typed ``section.key`` from ``rebar._config_schema._SECTIONS`` plus every
live canonical environment variable name derived by
``rebar.config._canonical_env_name``. Deprecated aliases and removed tombstones are
validated by tests against their own registries; they are deliberately NOT emitted
here because this file exists to prove the live surface is enrolled in the removal
oracle in both directions.

Usage:
    python scripts/generate_config_surface_golden.py
    python scripts/generate_config_surface_golden.py --check
    python scripts/generate_config_surface_golden.py --output path/to/file.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "tests" / "golden" / "config_surface.json"
GEN_CMD = "python scripts/generate_config_surface_golden.py"
_COMMENT = (
    "Generated by `python scripts/generate_config_surface_golden.py` — do not edit by hand. "
    "This golden inventories the LIVE canonical config keys and canonical environment names "
    "derived from rebar._config_schema._SECTIONS and rebar.config._canonical_env_name. "
    "Alias and tombstone coverage is validated separately in "
    "tests/unit/test_config_surface_golden.py."
)


def _load_registries() -> None:
    """Resolve ``rebar.*`` imports from this checkout."""
    src = str(REPO_ROOT / "src")
    if src not in sys.path:
        sys.path.insert(0, src)


def _payload() -> dict[str, Any]:
    """Structured golden payload with deterministically-sorted live inventories."""
    _load_registries()
    from rebar._config_schema import _SECTIONS
    from rebar.config import _canonical_env_name

    config_keys = sorted(f"{section}.{key}" for section, keys in _SECTIONS.items() for key in keys)
    env_names = sorted(
        _canonical_env_name(section, key) for section, keys in _SECTIONS.items() for key in keys
    )
    return {
        "_comment": _COMMENT,
        "config_keys": config_keys,
        "canonical_env_vars": env_names,
    }


def render() -> str:
    """Stable JSON text with a trailing newline."""
    return json.dumps(_payload(), indent=2) + "\n"


def _is_stale(path: Path, generated: str) -> bool:
    """True when ``path`` does not already contain ``generated``."""
    if not path.exists():
        return True
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") != generated.replace("\r\n", "\n")


def _write(path: Path, generated: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generated, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the config-surface golden inventory.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the target file differs from the generated inventory",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="path to write/check instead of tests/golden/config_surface.json",
    )
    args = parser.parse_args(argv)

    generated = render()
    output = args.output
    if args.check:
        if _is_stale(output, generated):
            try:
                label = output.relative_to(REPO_ROOT)
            except ValueError:
                label = output
            sys.stderr.write(f"{label} is stale — regenerate with `{GEN_CMD}`\n")
            return 1
        return 0

    _write(output, generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
