#!/bin/sh
# Install Gerrit's commit-msg hook (the Change-Id stamper) SAFELY, from anywhere.
#
# Bug 84aa. The command this replaces —
#
#     curl -sLo "$(git rev-parse --git-path hooks/commit-msg)" <url>
#
# — is worktree-unsafe. Hooks live in the git COMMON dir, so from inside a linked
# worktree `--git-path hooks/commit-msg` resolves to the MAIN checkout's
# `.git/hooks/commit-msg` and the curl overwrites the shared, pre-commit-managed
# wrapper for EVERY worktree at once. `.pre-commit-config.yaml` documents the intended
# arrangement (pre-commit MIGRATION mode: the wrapper at `commit-msg` chained to the
# Gerrit stamper at `commit-msg.legacy`) and warns that dropping it "would drop the
# Change-Id stamp and break every push to Gerrit". The failure is silent at commit time
# and only surfaces at `git push gerrit`, possibly in a different worktree.
#
# This script is cwd-independent (it resolves the common dir deliberately),
# non-destructive (it never writes over a hook it did not put there), and idempotent
# (already-working Change-Id stamping is a no-op).
#
# Usage:   scripts/install-gerrit-hook.sh
# Env:     REBAR_GERRIT_HOOK_URL     override the download URL
#          REBAR_GERRIT_HOOK_SOURCE  install from a LOCAL file instead of downloading
#                                    (offline installs and the test suite)

set -eu

url="${REBAR_GERRIT_HOOK_URL:-https://rebar.solutions.navateam.com/tools/hooks/commit-msg}"

common="$(git rev-parse --git-common-dir)" || {
    echo "ERROR: not inside a git repository." >&2
    exit 1
}
# `--git-common-dir` may be relative (plain ".git" at the top of the main checkout);
# absolutise it so the script works from any subdirectory or worktree.
case "$common" in
    /*) ;;
    *) common="$(cd "$common" && pwd)" ;;
esac
hooks_dir="$common/hooks"
wrapper="$hooks_dir/commit-msg"
legacy="$hooks_dir/commit-msg.legacy"

stamps_change_id() {
    [ -f "$1" ] && grep -q 'Change-Id' "$1" 2>/dev/null
}

if stamps_change_id "$wrapper"; then
    echo "✓ Gerrit Change-Id stamping already installed ($wrapper)"
    exit 0
fi
if stamps_change_id "$legacy"; then
    echo "✓ Gerrit Change-Id stamping already installed ($legacy, chained by pre-commit)"
    exit 0
fi

target="$wrapper"
if [ -e "$wrapper" ]; then
    if grep -q 'generated by pre-commit' "$wrapper" 2>/dev/null; then
        # The pre-commit wrapper owns the `commit-msg` slot and runs `commit-msg.legacy`
        # after its own hooks. Installing into .legacy is what keeps BOTH gates alive.
        target="$legacy"
        echo "note: pre-commit owns $wrapper — installing the Gerrit hook as"
        echo "      $target (pre-commit's migration chain runs both)."
    else
        # Loud refusal rather than a silent clobber: this is the exact failure this
        # script exists to prevent.
        echo "ERROR: refusing to overwrite the existing commit-msg hook at" >&2
        echo "         $wrapper" >&2
        echo "       It is not a pre-commit wrapper and does not stamp a Change-Id, so" >&2
        echo "       overwriting it would silently destroy whatever it does. Inspect it," >&2
        echo "       move it aside (or to commit-msg.legacy), then re-run this script." >&2
        exit 1
    fi
fi

tmp="$(mktemp "${TMPDIR:-/tmp}/rebar-commit-msg.XXXXXX")"
trap 'rm -f "$tmp"' EXIT INT TERM

if [ -n "${REBAR_GERRIT_HOOK_SOURCE:-}" ]; then
    cp "$REBAR_GERRIT_HOOK_SOURCE" "$tmp"
elif ! curl -fsSL --max-time 20 -o "$tmp" "$url"; then
    echo "ERROR: could not download the Gerrit commit-msg hook from $url" >&2
    echo "       Pushes to Gerrit will be rejected for a missing Change-Id until this" >&2
    echo "       succeeds. Check network/VPN access to the Gerrit host and re-run:" >&2
    echo "         make hooks" >&2
    exit 1
fi

# Never install an HTML error page or a truncated body as a git hook.
if ! stamps_change_id "$tmp"; then
    echo "ERROR: the fetched hook does not contain any Change-Id logic — refusing to" >&2
    echo "       install it (an error page or a truncated download?). Source: $url" >&2
    exit 1
fi

chmod +x "$tmp"
mv "$tmp" "$target"
trap - EXIT INT TERM
echo "✓ Gerrit Change-Id stamping installed at $target"
