"""Contract: every rendered (help-backed) route pins a version-stable formatter.

RP-05 residual gap (db7f). The canonical help artifacts under
``src/rebar/_cli/help/*.txt`` are GENERATED by ``scripts/gen_cli_help.py`` from the
help-backed routes (``route.group != "intercept"``, not hidden, not retired) by
resolving each route's ``parser_factory`` and formatting its ``--help``. If any such
factory renders through the stdlib ``argparse.HelpFormatter`` instead of
``RebarHelpFormatter``, its output is neither width-pinned nor py3.13-pinned, so the
generated artifact can silently drift on the py3.13 CI cell (the exact ``--check``
staleness S2d fixed) and renders at width 78 rather than the canonical width 80.

This guard fails if any help-backed route's factory formatter is not a subclass of
``RebarHelpFormatter``. It is scoped to help-backed routes on purpose: intercept-group
routes carry no committed artifact and are already canonicalized cross-version by
``scripts/gen_cli_reference.py``. The scope self-adjusts — if a route later moves into
a rendered group, this guard begins covering it.
"""

from __future__ import annotations

import importlib

import pytest

from rebar._cli._parser import RebarHelpFormatter
from rebar._cli._registry import ROUTES


def _help_backed_routes() -> list:
    return [r for r in ROUTES if r.group != "intercept" and not r.hidden and not r.retired]


def _resolve_factory(ref: str):
    module_name, _, attr = ref.partition(":")
    return getattr(importlib.import_module(module_name), attr)


@pytest.mark.parametrize(
    "route",
    _help_backed_routes(),
    ids=lambda r: r.name,
)
def test_help_backed_factory_pins_rebar_formatter(route) -> None:
    """Each rendered route's parser uses a RebarHelpFormatter-derived formatter."""
    factory = _resolve_factory(route.parser_factory)
    parser = factory(prog=f"rebar {route.name}")
    assert issubclass(parser.formatter_class, RebarHelpFormatter), (
        f"route {route.name!r} ({route.parser_factory}) renders help through "
        f"{parser.formatter_class!r}, which is not a subclass of RebarHelpFormatter; "
        "its generated help artifact is not version/width pinned."
    )
