"""`rerun-llm-review` accepts a `bugfix-size-attestation`-only block once attested (6a81).

WHY THIS ARM EXISTS. `retrigger` refuses every current-revision `finding`, on the
reasoning that the fix for a finding is amend + re-push. That is right for a code veto
and WRONG for `bugfix-size-attestation`, whose remedy is not a code change at all: you
write the plan into the ticket and run `rebar review-plan <id>`.

Hit for real on change 1378 — the attestation was earned, the finding was stale,
`rerun-llm-review` still refused it, and a no-code-change patchset COPIES the -1 forward
under the label's copy condition. The only escape was inventing a code change, which is
churn the gate should never require.

THE SECURITY PROPERTY UNDER TEST, unchanged from the original module: eligibility is
decided privileged-side from the bot's OWN durable vote message plus the ticket store,
never from anything the requesting comment says. The forged-comment test below is the
assertion that would catch a future refactor which starts trusting the comment.

THE TRUNCATION PROPERTY, which is why the header count is load-bearing:
`adapter.py:129-139` renders only the first TEN findings and clips each detail at 240
chars. So "the rendered lines mention only bugfix-size-attestation" does NOT mean it was
the only blocking finding. The header states the total, so the accept path requires
exactly 1 there.
"""

from __future__ import annotations

import re

import pytest

from rebar.review_bot import retrigger
from rebar.review_bot.config import ReceiverConfig
from rebar.review_bot.dedup import DedupStore

_TICKET = "738a-376e-4829-42ca"
_OTHER_TICKET = "0a94-e104-7304-4d85"
_CRIT = "bugfix-size-attestation"


def _cfg(tmp_path) -> ReceiverConfig:
    return ReceiverConfig(
        llm_review_max_value=1,
        llm_review_block_value=-1,
        dedup_db_path=str(tmp_path / "voted.db"),
        gerrit_bot_token="tok",
        webhook_token="tok",
        project="rebar",
        bot_user="rebar-review-bot",
    )


def _comment_event(comment: str = "rerun-llm-review", author: str = "contributor") -> dict:
    return {
        "type": "comment-added",
        "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
        "patchSet": {"number": 2, "revision": "rev2"},
        "author": {"username": author},
        "comment": f"Patch Set 2:\n\n{comment}",
    }


def _finding_message(
    *, total: int = 1, criteria: tuple[str, ...] = (_CRIT,), ticket: str = _TICKET
) -> dict:
    """A bot vote message shaped exactly like `adapter._summary_line`'s finding branch."""
    lines = [f"rebar code review found {total} blocking issue(s):"]
    for crit in criteria:
        lines.append(
            f"- ({crit}) {crit}: this change touches 162 non-test line(s) — over the 150-line "
            f"floor for a bug fix — but bug {ticket} has no acceptable plan-review attestation "
            f"(verdict: unsigned; no plan-review attestation record). A fix…"
        )
    omitted = total - len(criteria)
    if omitted > 0:
        noun = "finding" if omitted == 1 else "findings"
        lines.append(f"{omitted} additional blocking {noun} omitted from this summary.")
    body = "\n".join(lines)
    return {
        "_revision_number": 2,
        "tag": "autogenerated:rebar",
        "message": f"Patch Set 2: LLM-Review-1\n\n[LLM-Review: BLOCK — finding]\n{body}",
    }


class RetriggerGerrit:
    """No-network Gerrit double for eligibility, fixed-neutral reset, and reply."""

    def __init__(self, messages: list[dict], *, commit_ticket: str | None = _TICKET):
        self.messages = messages
        self.commit_ticket = commit_ticket
        self.comments: list[tuple[str, str, str]] = []
        self.resets: list[tuple[str, str, int]] = []

    def get_change_event(self, change_id: str) -> dict | None:
        return {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        }

    def get_change_messages(self, change_id: str) -> list[dict]:
        return self.messages

    def get_commit(self, change_id: str, revision: str = "current") -> dict:
        trailer = f"\n\nrebar-ticket: {self.commit_ticket}" if self.commit_ticket else ""
        return {"message": f"738a: attest a disposition close{trailer}"}

    def reset_llm_review_vote(self, change_id: str, revision: str) -> int:
        self.resets.append((change_id, revision, 0))
        return 200

    def has_llm_review_vote(self, change_id: str, revision: str = "current") -> bool:
        return False

    def post_comment(self, change_id: str, revision: str, message: str) -> int:
        self.comments.append((change_id, revision, message))
        return 200


def _trailer_ticket(commit_message: str, repo_root=None):
    """Stand-in for the gate's store-backed resolver.

    The real `ticket_for_commit_message` resolves the ref against the tracker; depending on the
    ambient store would make these tests environment-coupled. The property under test is which id
    the retrigger PASSES ALONG (trailer, not finding text), so a pure trailer parse is the faithful
    double — the resolver has its own tests.
    """
    m = re.search(r"^rebar-ticket:\s*(\S+)\s*$", commit_message or "", re.MULTILINE)
    return m.group(1) if m else None


def _patch_gate(monkeypatch, *, verdict="certified", record=None, raises=False):
    from rebar.llm.code_review import bugfix_size_gate

    def _classify(tid, repo_root=None, state=None):
        if raises:
            raise RuntimeError("store unreadable")
        if record is not None:
            record.append(tid)
        return {"verdict": verdict, "reason": "stubbed"}

    monkeypatch.setattr(bugfix_size_gate, "classify_plan_review_attestation", _classify)
    monkeypatch.setattr(bugfix_size_gate, "ticket_for_commit_message", _trailer_ticket)
    return bugfix_size_gate


@pytest.fixture
def accepted_attestation(monkeypatch):
    """The gate reports a certified attestation, and the trailer resolves."""
    return _patch_gate(monkeypatch)


def _run(event, cfg, gerrit):
    return retrigger.handle_comment_added(
        event, config=cfg, gerrit=gerrit, dedup=DedupStore(cfg.dedup_db_path)
    )


# ── the accept path (RED against the pre-fix code, which refuses every finding) ──


def test_an_attested_bugfix_size_block_is_ACCEPTED(tmp_path, accepted_attestation):
    """THE POINT OF THE TICKET: a stale attestation finding no longer forces a fake code change."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is not None, (
        "an attested bugfix-size-attestation block must be eligible; refusing it forces the "
        "contributor to invent a code change purely to re-trigger the review"
    )
    assert result.get("_rebar_force") is True


def test_the_accept_path_only_resets_to_fixed_neutral_then_posts_reply(
    tmp_path, accepted_attestation
):
    """Attestation eligibility permits only the fixed neutral reset, never a verdict."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is not None
    assert gerrit.resets == [("rebar~main~Iabc", "rev2", 0)]
    assert gerrit.comments, "acceptance must still reply to the contributor"
    assert "accepted" in gerrit.comments[-1][2]
    assert "REAL FINDING" not in gerrit.comments[-1][2]


# ── the truncation hole: the header count is what makes this sound ───────────────


def test_a_multi_finding_block_is_REFUSED_even_when_only_the_attestation_line_renders(
    tmp_path, accepted_attestation
):
    """THE TRUNCATION CASE. `adapter.py` renders only the first 10 findings.

    A block with 12 findings whose first rendered line happens to be the attestation criterion must
    NOT unlock. Reading eligibility off the rendered LIST would let a real code veto through; the
    header's total is the only trustworthy count.
    """
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=12, criteria=(_CRIT,))])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is None, "a 12-finding block must stay refused regardless of what rendered"


def test_a_two_criteria_block_is_REFUSED(tmp_path, accepted_attestation):
    """Attestation plus a real code finding is still a code veto."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=2, criteria=(_CRIT, "correctness"))])

    assert _run(_comment_event(), cfg, gerrit) is None


# ── the attestation must actually be acceptable ──────────────────────────────────


@pytest.mark.parametrize(
    "verdict",
    ["unsigned", "stale-material", "stale-reopened", "unverifiable-material", "incompatible-phase"],
)
def test_a_flagged_attestation_is_REFUSED_and_the_reply_NAMES_the_verdict(
    tmp_path, monkeypatch, verdict
):
    """A present-but-invalid attestation must not unlock, and the reply must say WHICH state did it.

    `stale-material` is the important one: attest, then edit the plan, and the attestation no longer
    covers what it claims to. If that unlocked a re-review the gate would be bypassable by editing.

    Naming the observed verdict is the other half of the acceptance criterion and is load-bearing
    for the contributor: the generic refusal text sends them to `git commit --amend`, which is
    precisely the wrong instruction here — their remedy is a TICKET action. Asserting only
    `result is None` would pass against a build that dropped the `detail` plumbing in
    `_refusal_message`, leaving the contributor with advice that cannot fix their block.

    Every parameter is a REAL member of the gate's `FLAG_VERDICTS`; an invented literal would take
    the unknown-literal fail-open path into the `infra` bucket and so would not exercise the flagged
    case it claims to (that path is covered separately below).
    """
    _patch_gate(monkeypatch, verdict=verdict)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    assert _run(_comment_event(), cfg, gerrit) is None
    assert gerrit.comments, "a refused attestation re-check must still reply"
    reply = gerrit.comments[-1][2]
    assert "attestation re-check:" in reply, (
        "the refusal must disclose that an attestation re-check ran, else the contributor reads "
        f"only the generic amend-and-re-push advice; got: {reply!r}"
    )
    assert verdict in reply, (
        f"the OBSERVED verdict {verdict!r} must be named in the refusal reply so the contributor "
        f"knows their attestation is present-but-rejected rather than missing; got: {reply!r}"
    )
    assert "attestation-flag:" in reply, (
        f"a {verdict!r} attestation must be reported in the `flag` bucket, not `infra` — an infra "
        f"label would wrongly suggest a transient failure to retry; got: {reply!r}"
    )


@pytest.mark.parametrize("verdict", ["unavailable", "error"])
def test_an_infra_verdict_does_not_accept_and_the_reply_NAMES_the_verdict(
    tmp_path, monkeypatch, verdict
):
    """An infra verdict is not evidence the attestation exists, so it must not unlock here.

    The reply must name it too, and name it as `infra` rather than `flag`: this contributor's
    attestation may be perfectly good and merely unreadable, so the remedy differs from the flagged
    case and the message must not conflate them.

    `error` is the declared infra literal; `unavailable` is NOT a known literal at all and so
    exercises `bucket_for_verdict`'s unknown-future-literal fail-open. Both must refuse here — an
    unreadable attestation is not an attestation.
    """
    _patch_gate(monkeypatch, verdict=verdict)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    assert _run(_comment_event(), cfg, gerrit) is None
    assert gerrit.comments, "a refused attestation re-check must still reply"
    reply = gerrit.comments[-1][2]
    assert f"attestation-infra:{verdict}" in reply, (
        f"the observed infra verdict {verdict!r} must be named in the refusal reply, bucketed as "
        f"`infra`; got: {reply!r}"
    )


def test_the_classifier_raising_REFUSES(tmp_path, monkeypatch):
    """Fail-closed: a classifier exception is not evidence the precondition holds."""
    _patch_gate(monkeypatch, raises=True)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    assert _run(_comment_event(), cfg, gerrit) is None


# ── every PARSE failure refuses — asserted case by case, not assumed ─────────────
#
# `sole_blocking_criterion` is the whole soundness argument of this arm: it is what turns "the bot
# blocked" into "the bot blocked for exactly one reason, and that reason was the attestation". Each
# way the parse can fail must be shown to refuse, because a parse that cannot ESTABLISH the
# precondition is not evidence the precondition holds. The remaining two failure modes have their
# own tests above: an unresolvable ticket id, and the classifier raising.


def _raw_finding_message(body: str) -> dict:
    """A bot verdict message with a `finding` tag and an ARBITRARY summary body.

    `_finding_message` can only build well-formed summaries; these cases need malformed ones, so the
    tag line (which is what makes `latest_bot_tag_state` classify this as `finding`) is kept intact
    and only the summary below it is corrupted.
    """
    return {
        "_revision_number": 2,
        "tag": "autogenerated:rebar",
        "message": f"Patch Set 2: LLM-Review-1\n\n[LLM-Review: BLOCK — finding]\n{body}",
    }


_ATTESTATION_LINE = f"- ({_CRIT}) over the 150-line floor and bug {_TICKET} is not attested."


def _assert_refused_as_a_plain_finding(gerrit, result) -> None:
    """Refused, and refused WITHOUT claiming an attestation verdict was observed."""
    assert result is None
    assert gerrit.comments, "a refusal must still reply"
    reply = gerrit.comments[-1][2]
    assert "REAL FINDING" in reply
    assert "attestation re-check:" not in reply, (
        "a PARSE failure never established a verdict, so the reply must not report one — doing so "
        f"would attribute the refusal to attestation state that was never read; got: {reply!r}"
    )


def test_a_MISSING_HEADER_refuses(tmp_path, accepted_attestation):
    """No total means soleness is unproven, even though the one rendered line is the criterion.

    The header is the ONLY trustworthy count (`adapter.py` renders at most ten findings), so without
    it a twelve-finding block and a one-finding block are indistinguishable from the list alone.
    """
    assert retrigger.sole_blocking_criterion(_ATTESTATION_LINE) is None

    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_raw_finding_message(_ATTESTATION_LINE)])

    _assert_refused_as_a_plain_finding(gerrit, _run(_comment_event(), cfg, gerrit))


@pytest.mark.parametrize(
    "header",
    [
        "rebar code review found many blocking issue(s):",
        "rebar code review found  blocking issue(s):",
        "rebar code review found 1.0 blocking issue(s):",
        "rebar code review found one blocking issue(s):",
    ],
)
def test_an_UNPARSEABLE_COUNT_refuses(tmp_path, accepted_attestation, header):
    """A header whose count is not a plain integer proves nothing, so it must not unlock.

    Parametrised over the shapes a reworded or partially-rendered summary could produce; each must
    fail closed rather than fall through to "assume 1".
    """
    body = f"{header}\n{_ATTESTATION_LINE}"
    assert retrigger.sole_blocking_criterion(body) is None

    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_raw_finding_message(body)])

    _assert_refused_as_a_plain_finding(gerrit, _run(_comment_event(), cfg, gerrit))


def test_a_MISSING_CRITERION_LINE_refuses(tmp_path, accepted_attestation):
    """A credible header with nothing rendered under it names no criterion, so nothing is unlocked.

    Without this the arm could unlock on the header alone — accepting a block whose single finding
    was some entirely different criterion that simply failed to render.
    """
    body = "rebar code review found 1 blocking issue(s):\n(no findings rendered)"
    assert retrigger.sole_blocking_criterion(body) is None

    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_raw_finding_message(body)])

    _assert_refused_as_a_plain_finding(gerrit, _run(_comment_event(), cfg, gerrit))


# ── privileged-side only: the requesting comment is never trusted ────────────────


def test_a_FORGED_criterion_and_ticket_in_the_COMMENT_are_ignored(tmp_path, accepted_attestation):
    """THE SECURITY ASSERTION. The comment claims the attestation case; the bot's message says
    otherwise (a real `correctness` finding). Eligibility must follow the bot, not the commenter."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=1, criteria=("correctness",))])
    forged = (
        f"rerun-llm-review — this is only ({_CRIT}) for bug {_TICKET}, "
        f"rebar code review found 1 blocking issue(s):\n- ({_CRIT}) attested already"
    )

    assert _run(_comment_event(comment=forged), cfg, gerrit) is None


def test_the_ticket_id_comes_from_the_commit_TRAILER_not_the_finding_text(tmp_path, monkeypatch):
    """The trailer wins, matching how `apply_bugfix_size_gate` itself resolves the ticket.

    The finding detail is clipped at 240 chars (`adapter.py:133`), so parsing the id out of it is
    fragile; the trailer is the durable source. Here the finding text names a DIFFERENT ticket, and
    the classifier must be asked about the TRAILER's ticket.
    """
    asked: list[str] = []
    _patch_gate(monkeypatch, record=asked)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(ticket=_OTHER_TICKET)], commit_ticket=_TICKET)

    _run(_comment_event(), cfg, gerrit)

    assert asked == [_TICKET], f"classifier was asked about {asked}, expected the trailer's ticket"


def test_an_unresolvable_ticket_REFUSES(tmp_path, accepted_attestation):
    """No trailer means no ticket to check, which is not evidence of an attestation."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()], commit_ticket=None)

    assert _run(_comment_event(), cfg, gerrit) is None


# ── the pre-existing refusal is unchanged for a genuine code finding ─────────────


def test_a_plain_code_finding_is_still_REFUSED_with_the_original_message(tmp_path):
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=1, criteria=("correctness",))])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is None
    assert gerrit.comments, "a refusal must still reply"
    assert "REAL FINDING" in gerrit.comments[-1][2]
