"""Bug 84aa: the Gerrit commit-msg hook install must be worktree-safe.

The command AGENTS.md and CONTRIBUTING.md used to document —

    curl -sLo "$(git rev-parse --git-path hooks/commit-msg)" <url>

— resolves, from inside a LINKED WORKTREE, to the MAIN checkout's shared
``.git/hooks/commit-msg``. That is the slot pre-commit's wrapper occupies, so the curl
silently clobbers the wrapper for EVERY worktree on the host, dropping either the
pre-commit ``commit-msg`` gate or (after the next ``pre-commit install``) the Change-Id
stamp. The damage is invisible until a Gerrit push is rejected, possibly in a different
worktree than the one that ran the command. Two independent agents hit this in one
session.

These tests pin both halves: that the shared slot really is what the old path targets
(the defect), and that ``scripts/install-gerrit-hook.sh`` leaves BOTH hooks working when
run from inside a worktree (the fix).
"""

from __future__ import annotations

import stat
import subprocess
from pathlib import Path

import pytest
from _subprocess_env import subprocess_env

REPO_ROOT = Path(__file__).resolve().parents[2]
INSTALLER = REPO_ROOT / "scripts" / "install-gerrit-hook.sh"

# A stand-in for Gerrit's real commit-msg hook: the test pins the WIRING (which slot the
# installer writes, and that the chain still runs), not Gerrit's script itself, so it
# stays hermetic and offline.
FAKE_GERRIT_HOOK = """#!/bin/sh
grep -q '^Change-Id:' "$1" && exit 0
printf 'Change-Id: I%s\\n' "0000000000000000000000000000000000000001" >> "$1"
"""

# A stand-in for the pre-commit wrapper. It carries pre-commit's own marker line (which
# is how the installer recognises the slot as owned) and reproduces migration mode:
# run our gate, then chain to commit-msg.legacy.
FAKE_PRECOMMIT_WRAPPER = """#!/bin/sh
# File generated by pre-commit: https://pre-commit.com
echo "precommit-commit-msg-gate ran" >> "$(dirname "$0")/../../precommit-gate.log"
HERE="$(cd "$(dirname "$0")" && pwd)"
if [ -x "$HERE/commit-msg.legacy" ]; then
    exec "$HERE/commit-msg.legacy" "$@"
fi
"""


def _write_hook(path: Path, body: str) -> None:
    path.write_text(body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _git(*args: str, cwd: Path) -> str:
    proc = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True, timeout=60
    )
    return proc.stdout


@pytest.fixture
def checkout_with_worktree(tmp_path: Path) -> tuple[Path, Path, Path]:
    """A main checkout carrying a pre-commit wrapper, plus a LINKED worktree.

    Returns ``(main, worktree, shared_hooks_dir)``.
    """
    main = tmp_path / "main"
    main.mkdir()
    _git("init", "-q", "-b", "main", cwd=main)
    _git("config", "user.email", "test@example.com", cwd=main)
    _git("config", "user.name", "Test", cwd=main)
    _git("config", "commit.gpgsign", "false", cwd=main)
    (main / "README.md").write_text("seed\n", encoding="utf-8")
    _git("add", "README.md", cwd=main)
    _git("-c", "core.hooksPath=/dev/null", "commit", "-q", "-m", "seed", cwd=main)

    hooks = main / ".git" / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    _write_hook(hooks / "commit-msg", FAKE_PRECOMMIT_WRAPPER)

    worktree = tmp_path / "linked"
    _git("worktree", "add", "-q", "-b", "feature", str(worktree), cwd=main)
    return main, worktree, hooks


def test_the_old_documented_path_targets_the_shared_precommit_slot(
    checkout_with_worktree: tuple[Path, Path, Path],
) -> None:
    """The defect itself, pinned so nobody reintroduces the bare curl.

    ``git rev-parse --git-path hooks/commit-msg`` run from a LINKED worktree points at the
    MAIN checkout's shared hook file — the very file pre-commit's wrapper occupies. Any
    ``curl -o`` at that path is therefore a host-wide clobber, not a per-worktree install.
    """
    _main, worktree, hooks = checkout_with_worktree

    resolved = Path(_git("rev-parse", "--git-path", "hooks/commit-msg", cwd=worktree).strip())
    if not resolved.is_absolute():
        resolved = (worktree / resolved).resolve()

    assert resolved == (hooks / "commit-msg").resolve(), (
        "the old documented path was expected to resolve to the MAIN checkout's shared "
        f"hook; got {resolved}"
    )
    assert "generated by pre-commit" in resolved.read_text(encoding="utf-8"), (
        "the shared slot holds the pre-commit wrapper — a curl over it destroys it"
    )
    assert resolved.parent != (worktree / ".git" / "hooks"), (
        "hooks are NOT per-worktree; the install cannot be scoped by cd-ing into one"
    )

    # Perform the old command's write (with a stand-in payload instead of a download)
    # to show the damage concretely: the shared wrapper is gone, host-wide.
    _write_hook(resolved, FAKE_GERRIT_HOOK)
    assert "generated by pre-commit" not in (hooks / "commit-msg").read_text(encoding="utf-8"), (
        "the old documented curl was expected to DESTROY the shared pre-commit wrapper; "
        "if this no longer holds, the premise of bug 84aa has changed"
    )


def test_installer_from_a_worktree_leaves_both_hooks_working(
    checkout_with_worktree: tuple[Path, Path, Path], tmp_path: Path
) -> None:
    """AC1 + AC2: run the documented install from inside a linked worktree, then commit
    there. The commit must receive a Change-Id AND still pass through the pre-commit
    ``commit-msg`` gate."""
    main, worktree, hooks = checkout_with_worktree
    source = tmp_path / "gerrit-commit-msg"
    _write_hook(source, FAKE_GERRIT_HOOK)
    wrapper_before = (hooks / "commit-msg").read_bytes()

    env = subprocess_env(REBAR_GERRIT_HOOK_SOURCE=str(source))
    result = subprocess.run(
        ["sh", str(INSTALLER)],
        cwd=worktree,
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, f"installer failed: {result.stdout}\n{result.stderr}"

    assert (hooks / "commit-msg").read_bytes() == wrapper_before, (
        "the installer overwrote the shared pre-commit wrapper — this is bug 84aa"
    )
    assert (hooks / "commit-msg.legacy").is_file(), (
        "the Gerrit stamper must land in the .legacy slot pre-commit chains to"
    )

    (worktree / "change.txt").write_text("work\n", encoding="utf-8")
    _git("add", "change.txt", cwd=worktree)
    _git("commit", "-q", "-m", "worktree: a change", cwd=worktree)

    message = _git("log", "-1", "--format=%B", cwd=worktree)
    assert "Change-Id: I" in message, (
        f"the commit made in the worktree got no Change-Id — Gerrit would reject it: {message!r}"
    )
    assert (main / "precommit-gate.log").is_file(), (
        "the pre-commit commit-msg gate did not run — the installer broke the chain"
    )


def test_installer_is_idempotent(
    checkout_with_worktree: tuple[Path, Path, Path], tmp_path: Path
) -> None:
    """``make hooks`` runs on every ``make install``, so a second install must be a no-op
    rather than a re-download that could land in a different slot."""
    _main, worktree, hooks = checkout_with_worktree
    source = tmp_path / "gerrit-commit-msg"
    _write_hook(source, FAKE_GERRIT_HOOK)
    env = subprocess_env(REBAR_GERRIT_HOOK_SOURCE=str(source))

    for _ in range(2):
        assert (
            subprocess.run(
                ["sh", str(INSTALLER)], cwd=worktree, env=env, capture_output=True, timeout=60
            ).returncode
            == 0
        )

    assert "generated by pre-commit" in (hooks / "commit-msg").read_text(encoding="utf-8")
    assert (hooks / "commit-msg.legacy").is_file()


def test_installer_refuses_to_clobber_an_unrecognized_commit_msg_hook(
    checkout_with_worktree: tuple[Path, Path, Path], tmp_path: Path
) -> None:
    """AC4: the unsafe overwrite must be LOUD. A third-party ``commit-msg`` hook that is
    neither a pre-commit wrapper nor a Change-Id stamper is refused, not replaced."""
    _main, worktree, hooks = checkout_with_worktree
    _write_hook(hooks / "commit-msg", "#!/bin/sh\necho someone-elses-hook\n")
    source = tmp_path / "gerrit-commit-msg"
    _write_hook(source, FAKE_GERRIT_HOOK)

    result = subprocess.run(
        ["sh", str(INSTALLER)],
        cwd=worktree,
        env=subprocess_env(REBAR_GERRIT_HOOK_SOURCE=str(source)),
        capture_output=True,
        text=True,
        timeout=60,
    )

    assert result.returncode != 0, "an unsafe overwrite must fail loudly, not succeed quietly"
    assert "refusing to overwrite" in result.stderr
    assert (hooks / "commit-msg").read_text(encoding="utf-8") == (
        "#!/bin/sh\necho someone-elses-hook\n"
    ), "the pre-existing hook must be left untouched"


def test_docs_no_longer_instruct_the_worktree_unsafe_curl() -> None:
    """AC3: AGENTS.md and CONTRIBUTING.md must not tell contributors to curl over the
    shared hook slot — neither via ``--git-path hooks/commit-msg`` nor via a bare
    ``.git/hooks/commit-msg`` path, which is the same file by another spelling."""
    offenders: list[str] = []
    for name in ("AGENTS.md", "CONTRIBUTING.md"):
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        for lineno, line in enumerate(text.splitlines(), 1):
            if "curl" not in line:
                continue
            if "git-path hooks/commit-msg" in line or ".git/hooks/commit-msg" in line:
                offenders.append(f"{name}:{lineno}: {line.strip()}")
    assert not offenders, (
        "docs still instruct the worktree-unsafe curl over the shared commit-msg slot; "
        "point at `make hooks` instead:\n  " + "\n  ".join(offenders)
    )
