"""Tests for the locked build-environment checker.

The checker compares normalized installed package names and versions with the lock file,
excluding the documented base packages. Its command exits nonzero and names each missing or
mismatched package.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from _repo_root import REPO_ROOT

SCRIPT = REPO_ROOT / "scripts" / "check_build_env_locked.py"

# A minimal hash-locked lock file (name==version + --hash lines + comments, like pip-compile).
LOCK = """\
# generated by pip-compile --generate-hashes
build==1.2.2.post1 \\
    --hash=sha256:aaaa
hatchling==1.27.0 \\
    --hash=sha256:bbbb
twine==6.1.0 \\
    --hash=sha256:cccc
"""


def _run(lock_text: str, freeze_text: str, tmp_path: Path) -> subprocess.CompletedProcess:
    lock = tmp_path / "release-requirements.txt"
    freeze = tmp_path / "freeze.txt"
    lock.write_text(lock_text)
    freeze.write_text(freeze_text)
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--lock", str(lock), "--freeze", str(freeze)],
        capture_output=True,
        text=True,
        check=False,
    )


# ── HAPPY PATH (implementer sees) ─────────────────────────────────────────────
def test_clean_env_passes(tmp_path: Path) -> None:
    # Installed set == lock (+ allowlisted base pkgs) -> exit 0.
    freeze = (
        "build==1.2.2.post1\nhatchling==1.27.0\ntwine==6.1.0\n"
        "pip==24.0\nsetuptools==70.0\nwheel==0.43\n"
    )
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode == 0, f"clean env should pass: {cp.stdout}{cp.stderr}"


# ══════════════════════════════════════════════════════════════════════════════
#  HELD-OUT ORACLE (edge cases)
# ══════════════════════════════════════════════════════════════════════════════
def test_extra_unlocked_package_fails(tmp_path: Path) -> None:
    # An installed package absent from the lock (and not allowlisted) -> non-zero.
    freeze = "build==1.2.2.post1\nhatchling==1.27.0\ntwine==6.1.0\nrequests==2.32.0\n"
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode != 0, "an unlocked extra package must fail the guard"
    assert "requests" in (cp.stdout + cp.stderr).lower()


def test_version_mismatch_fails(tmp_path: Path) -> None:
    # An installed package at a different version than the lock -> non-zero.
    freeze = "build==1.2.2.post1\nhatchling==9.9.9\ntwine==6.1.0\n"
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode != 0, "a version mismatch must fail the guard"
    assert "hatchling" in (cp.stdout + cp.stderr).lower()


def test_base_allowlist_extras_pass(tmp_path: Path) -> None:
    # pip/setuptools/wheel are allowlisted even when absent from the lock -> exit 0.
    freeze = (
        "build==1.2.2.post1\nhatchling==1.27.0\ntwine==6.1.0\n"
        "pip==24.0\nsetuptools==70.0\nwheel==0.43\n"
    )
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode == 0, f"allowlisted base pkgs must not fail: {cp.stderr}"


def test_case_insensitive_name_match(tmp_path: Path) -> None:
    # Names compare case-insensitively (pip freeze may differ in case).
    freeze = "Build==1.2.2.post1\nHatchling==1.27.0\nTwine==6.1.0\n"
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode == 0, f"name match must be case-insensitive: {cp.stderr}"


# PEP 503 treats runs of hyphens, periods, and underscores as equivalent. Normalize both
# freeze and lock names before comparing them.
_NORM_LOCK = (
    "jaraco-classes==3.4.0 \\\n    --hash=sha256:aaaa\n"
    "readme-renderer==45.0 \\\n    --hash=sha256:bbbb\n"
    "pyproject-hooks==1.2.0 \\\n    --hash=sha256:cccc\n"
)


def test_pep503_dotted_and_underscored_names_match_hyphenated_lock(tmp_path: Path) -> None:
    # freeze uses dots/underscores; lock uses hyphens -> must be recognized as the same
    # pinned packages and pass (this is the exact real-world failure that was observed).
    freeze = "jaraco.classes==3.4.0\nreadme_renderer==45.0\npyproject_hooks==1.2.0\n"
    cp = _run(_NORM_LOCK, freeze, tmp_path)
    assert cp.returncode == 0, (
        f"PEP 503-equivalent names must match the hyphenated lock: {cp.stdout}{cp.stderr}"
    )


def test_pep503_normalized_version_mismatch_still_fails(tmp_path: Path) -> None:
    # Normalization must not mask a genuine version mismatch on the same (normalized) name.
    freeze = "jaraco.classes==9.9.9\nreadme_renderer==45.0\npyproject_hooks==1.2.0\n"
    cp = _run(_NORM_LOCK, freeze, tmp_path)
    assert cp.returncode != 0, "a version mismatch on a normalized name must still fail"
    assert "jaraco" in (cp.stdout + cp.stderr).lower()
