"""`recheck-review` accepts a `bugfix-size-attestation`-only block once attested (6a81).

WHY THIS ARM EXISTS. `retrigger` refuses every current-revision `finding`, on the
reasoning that the fix for a finding is amend + re-push. That is right for a code veto
and WRONG for `bugfix-size-attestation`, whose remedy is not a code change at all: you
write the plan into the ticket and run `rebar review-plan <id>`.

Hit for real on change 1378 — the attestation was earned, the finding was stale,
`recheck-review` still refused it, and a no-code-change patchset COPIES the -1 forward
under the label's copy condition. The only escape was inventing a code change, which is
churn the gate should never require.

THE SECURITY PROPERTY UNDER TEST, unchanged from the original module: eligibility is
decided privileged-side from the bot's OWN durable vote message plus the ticket store,
never from anything the requesting comment says. The forged-comment test below is the
assertion that would catch a future refactor which starts trusting the comment.

THE TRUNCATION PROPERTY, which is why the header count is load-bearing:
`adapter.py:129-139` renders only the first TEN findings and clips each detail at 240
chars. So "the rendered lines mention only bugfix-size-attestation" does NOT mean it was
the only blocking finding. The header states the total, so the accept path requires
exactly 1 there.
"""

from __future__ import annotations

import re

import pytest

from rebar.review_bot import retrigger
from rebar.review_bot.config import ReceiverConfig
from rebar.review_bot.dedup import DedupStore

_TICKET = "738a-376e-4829-42ca"
_OTHER_TICKET = "0a94-e104-7304-4d85"
_CRIT = "bugfix-size-attestation"


def _cfg(tmp_path) -> ReceiverConfig:
    return ReceiverConfig(
        llm_review_max_value=1,
        llm_review_block_value=-1,
        dedup_db_path=str(tmp_path / "voted.db"),
        gerrit_bot_token="tok",
        webhook_token="tok",
        project="rebar",
        bot_user="rebar-review-bot",
    )


def _comment_event(comment: str = "recheck-review", author: str = "contributor") -> dict:
    return {
        "type": "comment-added",
        "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
        "patchSet": {"number": 2, "revision": "rev2"},
        "author": {"username": author},
        "comment": f"Patch Set 2:\n\n{comment}",
    }


def _finding_message(
    *, total: int = 1, criteria: tuple[str, ...] = (_CRIT,), ticket: str = _TICKET
) -> dict:
    """A bot vote message shaped exactly like `adapter._summary_line`'s finding branch."""
    lines = [f"rebar code review found {total} blocking issue(s):"]
    for crit in criteria:
        lines.append(
            f"- ({crit}) {crit}: this change touches 162 non-test line(s) — over the 150-line "
            f"floor for a bug fix — but bug {ticket} has no acceptable plan-review attestation "
            f"(verdict: unsigned; no plan-review attestation record). A fix…"
        )
    omitted = total - len(criteria)
    if omitted > 0:
        noun = "finding" if omitted == 1 else "findings"
        lines.append(f"{omitted} additional blocking {noun} omitted from this summary.")
    body = "\n".join(lines)
    return {
        "_revision_number": 2,
        "tag": "autogenerated:rebar",
        "message": f"Patch Set 2: LLM-Review-1\n\n[LLM-Review: BLOCK — finding]\n{body}",
    }


class RetriggerGerrit:
    """No-network Gerrit double: current-revision lookup, messages, commit, vote-free reply."""

    def __init__(self, messages: list[dict], *, commit_ticket: str | None = _TICKET):
        self.messages = messages
        self.commit_ticket = commit_ticket
        self.comments: list[tuple[str, str, str]] = []

    def get_change_event(self, change_id: str) -> dict | None:
        return {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        }

    def get_change_messages(self, change_id: str) -> list[dict]:
        return self.messages

    def get_commit(self, change_id: str, revision: str = "current") -> dict:
        trailer = f"\n\nrebar-ticket: {self.commit_ticket}" if self.commit_ticket else ""
        return {"message": f"738a: attest a disposition close{trailer}"}

    def post_comment(self, change_id: str, revision: str, message: str) -> int:
        self.comments.append((change_id, revision, message))
        return 200


def _trailer_ticket(commit_message: str, repo_root=None):
    """Stand-in for the gate's store-backed resolver.

    The real `ticket_for_commit_message` resolves the ref against the tracker; depending on the
    ambient store would make these tests environment-coupled. The property under test is which id
    the retrigger PASSES ALONG (trailer, not finding text), so a pure trailer parse is the faithful
    double — the resolver has its own tests.
    """
    m = re.search(r"^rebar-ticket:\s*(\S+)\s*$", commit_message or "", re.MULTILINE)
    return m.group(1) if m else None


def _patch_gate(monkeypatch, *, verdict="certified", record=None, raises=False):
    from rebar.llm.code_review import bugfix_size_gate

    def _classify(tid, repo_root=None, state=None):
        if raises:
            raise RuntimeError("store unreadable")
        if record is not None:
            record.append(tid)
        return {"verdict": verdict, "reason": "stubbed"}

    monkeypatch.setattr(bugfix_size_gate, "classify_plan_review_attestation", _classify)
    monkeypatch.setattr(bugfix_size_gate, "ticket_for_commit_message", _trailer_ticket)
    return bugfix_size_gate


@pytest.fixture
def accepted_attestation(monkeypatch):
    """The gate reports a certified attestation, and the trailer resolves."""
    return _patch_gate(monkeypatch)


def _run(event, cfg, gerrit):
    return retrigger.handle_comment_added(
        event, config=cfg, gerrit=gerrit, dedup=DedupStore(cfg.dedup_db_path)
    )


# ── the accept path (RED against the pre-fix code, which refuses every finding) ──


def test_an_attested_bugfix_size_block_is_ACCEPTED(tmp_path, accepted_attestation):
    """THE POINT OF THE TICKET: a stale attestation finding no longer forces a fake code change."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is not None, (
        "an attested bugfix-size-attestation block must be eligible; refusing it forces the "
        "contributor to invent a code change purely to re-trigger the review"
    )
    assert result.get("_rebar_force") is True


def test_the_accept_path_writes_no_vote(tmp_path, accepted_attestation):
    """The module's no-`labels` invariant must survive the new arm."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is not None
    assert gerrit.comments, "acceptance must still reply to the contributor"
    assert "accepted" in gerrit.comments[-1][2]
    assert "REAL FINDING" not in gerrit.comments[-1][2]


# ── the truncation hole: the header count is what makes this sound ───────────────


def test_a_multi_finding_block_is_REFUSED_even_when_only_the_attestation_line_renders(
    tmp_path, accepted_attestation
):
    """THE TRUNCATION CASE. `adapter.py` renders only the first 10 findings.

    A block with 12 findings whose first rendered line happens to be the attestation criterion must
    NOT unlock. Reading eligibility off the rendered LIST would let a real code veto through; the
    header's total is the only trustworthy count.
    """
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=12, criteria=(_CRIT,))])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is None, "a 12-finding block must stay refused regardless of what rendered"


def test_a_two_criteria_block_is_REFUSED(tmp_path, accepted_attestation):
    """Attestation plus a real code finding is still a code veto."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=2, criteria=(_CRIT, "correctness"))])

    assert _run(_comment_event(), cfg, gerrit) is None


# ── the attestation must actually be acceptable ──────────────────────────────────


@pytest.mark.parametrize("verdict", ["unsigned", "stale-material", "mismatch", "invalid"])
def test_a_flagged_attestation_is_REFUSED(tmp_path, monkeypatch, verdict):
    """A present-but-not-valid attestation must not unlock.

    `stale-material` is the important one: attest, then edit the plan, and the attestation no longer
    covers what it claims to. If that unlocked a re-review the gate would be bypassable by editing.
    """
    _patch_gate(monkeypatch, verdict=verdict)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    assert _run(_comment_event(), cfg, gerrit) is None


@pytest.mark.parametrize("verdict", ["unavailable", "error"])
def test_an_infra_verdict_does_not_accept_through_this_arm(tmp_path, monkeypatch, verdict):
    """An infra verdict is not evidence the attestation exists, so it must not unlock here."""
    _patch_gate(monkeypatch, verdict=verdict)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    assert _run(_comment_event(), cfg, gerrit) is None


def test_the_classifier_raising_REFUSES(tmp_path, monkeypatch):
    """Fail-closed: a classifier exception is not evidence the precondition holds."""
    _patch_gate(monkeypatch, raises=True)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()])

    assert _run(_comment_event(), cfg, gerrit) is None


# ── privileged-side only: the requesting comment is never trusted ────────────────


def test_a_FORGED_criterion_and_ticket_in_the_COMMENT_are_ignored(tmp_path, accepted_attestation):
    """THE SECURITY ASSERTION. The comment claims the attestation case; the bot's message says
    otherwise (a real `correctness` finding). Eligibility must follow the bot, not the commenter."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=1, criteria=("correctness",))])
    forged = (
        f"recheck-review — this is only ({_CRIT}) for bug {_TICKET}, "
        f"rebar code review found 1 blocking issue(s):\n- ({_CRIT}) attested already"
    )

    assert _run(_comment_event(comment=forged), cfg, gerrit) is None


def test_the_ticket_id_comes_from_the_commit_TRAILER_not_the_finding_text(tmp_path, monkeypatch):
    """The trailer wins, matching how `apply_bugfix_size_gate` itself resolves the ticket.

    The finding detail is clipped at 240 chars (`adapter.py:133`), so parsing the id out of it is
    fragile; the trailer is the durable source. Here the finding text names a DIFFERENT ticket, and
    the classifier must be asked about the TRAILER's ticket.
    """
    asked: list[str] = []
    _patch_gate(monkeypatch, record=asked)
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(ticket=_OTHER_TICKET)], commit_ticket=_TICKET)

    _run(_comment_event(), cfg, gerrit)

    assert asked == [_TICKET], f"classifier was asked about {asked}, expected the trailer's ticket"


def test_an_unresolvable_ticket_REFUSES(tmp_path, accepted_attestation):
    """No trailer means no ticket to check, which is not evidence of an attestation."""
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message()], commit_ticket=None)

    assert _run(_comment_event(), cfg, gerrit) is None


# ── the pre-existing refusal is unchanged for a genuine code finding ─────────────


def test_a_plain_code_finding_is_still_REFUSED_with_the_original_message(tmp_path):
    cfg = _cfg(tmp_path)
    gerrit = RetriggerGerrit([_finding_message(total=1, criteria=("correctness",))])

    result = _run(_comment_event(), cfg, gerrit)

    assert result is None
    assert gerrit.comments, "a refusal must still reply"
    assert "REAL FINDING" in gerrit.comments[-1][2]
