"""Tests for the contributor-triggerable re-review (``rerun-llm-review``, ticket bb9b).

The security property under test: a ``rerun-llm-review`` comment can only cause the
privileged bot to write the fixed neutral ``LLM-Review: 0`` reset after eligibility,
and can NEVER choose a label value or get a real findings-BLOCK re-reviewed. Only
infrastructure states (every coverage-gap sub-reason, a retries-exhausted escalation,
a PASS, a vote-less or unparseable state) are eligible, decided privileged-side from
the bot's own durable vote-message tag on the CURRENT revision, never from the
requesting comment. Reply comments remain label-free.
"""

from __future__ import annotations

import configparser
import logging
from pathlib import Path

import pytest

from rebar.review_bot import retrigger
from rebar.review_bot.adapter import _TAG_SUFFIXES
from rebar.review_bot.config import ReceiverConfig
from rebar.review_bot.dedup import DedupStore
from rebar.review_bot.gerrit_client import GerritError


def _cfg(tmp_path) -> ReceiverConfig:
    return ReceiverConfig(
        llm_review_max_value=1,
        llm_review_block_value=-1,
        dedup_db_path=str(tmp_path / "voted.db"),
        gerrit_bot_token="tok",
        webhook_token="tok",
        project="rebar",
        bot_user="rebar-review-bot",
    )


def _comment_event(
    comment: str = "rerun-llm-review",
    author: str = "contributor",
    project: str = "rebar",
) -> dict:
    return {
        "type": "comment-added",
        "change": {"id": "rebar~main~Iabc", "number": 42, "project": project},
        "patchSet": {"number": 2, "revision": "rev2"},
        "author": {"username": author},
        "comment": f"Patch Set 2:\n\n{comment}",
    }


def _bot_message(tag_body: str, revision_number: int = 2, tag: str = "autogenerated:rebar") -> dict:
    return {
        "_revision_number": revision_number,
        "tag": tag,
        "message": f"Patch Set {revision_number}: LLM-Review-1\n\n[LLM-Review: {tag_body}]\nbody",
    }


class RetriggerGerrit:
    """No-network Gerrit double for the retrigger path: current-revision lookup, the
    change-message list, and the vote-free reply — recording everything posted."""

    def __init__(
        self,
        messages: list[dict] | None = None,
        *,
        change_exists: bool = True,
        has_vote: bool = False,
        reset_error: GerritError | None = None,
        read_error: GerritError | None = None,
        lookup_error: GerritError | None = None,
        messages_error: GerritError | None = None,
    ):
        self.messages = messages or []
        self.change_exists = change_exists
        self.has_vote = has_vote
        self.reset_error = reset_error
        self.read_error = read_error
        self.lookup_error = lookup_error
        self.messages_error = messages_error
        self.comments: list[tuple[str, str, str]] = []
        self.lookups: list[str] = []
        self.resets: list[tuple[str, str]] = []
        self.timeline: list[str] = []

    def get_change_event(self, change_id: str) -> dict | None:
        self.lookups.append(change_id)
        if self.lookup_error is not None:
            raise self.lookup_error
        if not self.change_exists:
            return None
        return {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        }

    def get_change_messages(self, change_id: str) -> list[dict]:
        self.timeline.append("eligibility")
        if self.messages_error is not None:
            raise self.messages_error
        return self.messages

    def reset_llm_review_vote(self, change_id: str, revision: str) -> int:
        self.timeline.append("reset_vote")
        self.resets.append((change_id, revision))
        if self.reset_error is not None:
            raise self.reset_error
        return 200

    def has_llm_review_vote(self, change_id: str, revision: str = "current") -> bool:
        self.timeline.append("verify_vote")
        if self.read_error is not None:
            raise self.read_error
        return self.has_vote

    def post_comment(self, change_id: str, revision: str, message: str) -> int:
        self.comments.append((change_id, revision, message))
        return 200


# ── the tag parser covers all three production tag shapes (AC2b) ────────────────


@pytest.mark.parametrize(
    ("tag_body", "expected"),
    [
        # (a) every _TAG_SUFFIXES member, straight from the vocabulary source of truth
        *[
            (
                suffix,
                "pass"
                if reason == "PASS"
                else ("finding" if reason == "finding" else f"coverage-gap:{reason}"),
            )
            for reason, suffix in _TAG_SUFFIXES.items()
        ],
        # (b) the hardcoded merge-review literal (voter._merge_coverage_gap_decision) —
        # NOT a _TAG_SUFFIXES member, must still classify
        ("BLOCK — coverage-gap (merge-review)", "coverage-gap:merge-review"),
        # (c) the in-tag merge-change suffix variant, applied to each stem kind
        ("PASS (merge-change, 3 integrated commit(s))", "pass"),
        ("BLOCK — finding (merge-change, 1 integrated commit(s))", "finding"),
        (
            "BLOCK — coverage-gap (review-error) (merge-change, 2 integrated commit(s))",
            "coverage-gap:review-error",
        ),
        # unknown-but-bracketed → unparseable (eligible, fail-open to a fresh review)
        ("SOMETHING NEW", "unparseable"),
    ],
)
def test_classify_tag_all_production_shapes(tag_body, expected):
    message = f"Patch Set 2: LLM-Review-1\n\n[LLM-Review: {tag_body}]\ntrailing body"
    assert retrigger.classify_tag(message) == expected


def test_classify_tag_absent_returns_none():
    assert retrigger.classify_tag("Patch Set 2:\n\njust words, no tag") is None
    assert retrigger.classify_tag(None) is None


def test_latest_bot_tag_state_filters_revision_and_tag():
    gerrit = RetriggerGerrit(
        messages=[
            _bot_message("BLOCK — finding", revision_number=1),  # OLD revision — ignored
            {"_revision_number": 2, "tag": None, "message": "[LLM-Review: PASS]"},  # not bot
            _bot_message("BLOCK — coverage-gap (review-error)", revision_number=2),
            _bot_message("PASS", revision_number=2),  # newest bot message wins
        ]
    )
    assert retrigger.latest_bot_tag_state(gerrit, "rebar~main~Iabc", 2) == "pass"


# ── AC2: findings-BLOCK is refused — bare AND merge tag forms ───────────────────


@pytest.mark.parametrize(
    "tag_body",
    ["BLOCK — finding", "BLOCK — finding (merge-change, 3 integrated commit(s))"],
)
def test_finding_block_is_refused(tmp_path, caplog, tag_body):
    gerrit = RetriggerGerrit(messages=[_bot_message(tag_body)])
    store = DedupStore(str(tmp_path / "voted.db"))
    store.record_attempt("rebar~main~Iabc", "rev2")

    with caplog.at_level(logging.WARNING, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )

    assert result is None  # no enqueue
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 1  # budget NOT reset
    assert len(gerrit.comments) == 1  # refusal reply posted…
    assert "REAL FINDING" in gerrit.comments[0][2]
    assert gerrit.resets == []  # eligibility is decided before any label write
    assert "RETRIGGER_REFUSED" in caplog.text
    assert "RETRIGGER_ACCEPTED" not in caplog.text


# ── AC1: eligible states re-arm the budget and enqueue a forced review ──────────


@pytest.mark.parametrize(
    "tag_body",
    [
        "BLOCK — coverage-gap (gate-disabled)",
        "BLOCK — coverage-gap (review-error)",  # incl. a 0347 retries-exhausted escalation
        "BLOCK — coverage-gap (merge-review)",
        "PASS",
    ],
)
def test_eligible_states_accept(tmp_path, caplog, tag_body):
    gerrit = RetriggerGerrit(messages=[_bot_message(tag_body)])
    store = DedupStore(str(tmp_path / "voted.db"))
    # Simulate the 0347 exhausted budget the human trigger must re-arm.
    for _ in range(3):
        store.record_attempt("rebar~main~Iabc", "rev2")

    with caplog.at_level(logging.INFO, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )

    assert result is not None and result["_rebar_force"] is True
    assert result["patchSet"]["revision"] == "rev2"  # the CURRENT revision, re-anchored
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 0  # budget re-armed
    assert gerrit.resets == [("rebar~main~Iabc", "rev2")]
    assert gerrit.timeline == ["eligibility", "reset_vote", "verify_vote"]
    assert len(gerrit.comments) == 1
    assert "queued" in gerrit.comments[0][2]
    assert "RETRIGGER_ACCEPTED" in caplog.text


def test_voteless_and_unparseable_states_are_eligible(tmp_path):
    for messages in ([], [_bot_message("SOMETHING NEW")]):
        gerrit = RetriggerGerrit(messages=messages)
        store = DedupStore(str(tmp_path / f"voted{len(messages)}.db"))
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )
        assert result is not None and result["_rebar_force"] is True


# ── AC3: loop guard + token no-ops (no Gerrit traffic at all) ───────────────────


def test_bot_own_comment_is_a_noop(tmp_path):
    gerrit = RetriggerGerrit(messages=[_bot_message("BLOCK — coverage-gap (review-error)")])
    result = retrigger.handle_comment_added(
        _comment_event(author="rebar-review-bot"),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is None
    assert gerrit.lookups == [] and gerrit.comments == []


@pytest.mark.parametrize(
    "comment",
    [
        "please rerun",
        "recheck",
        "rerun-llm-reviews",
        "pre-rerun-llm-review",
        "rerun-llm-review-x",
    ],
)
def test_non_matching_comment_is_a_noop(tmp_path, comment):
    gerrit = RetriggerGerrit()
    result = retrigger.handle_comment_added(
        _comment_event(comment=comment),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is None
    assert gerrit.lookups == [] and gerrit.comments == []


def test_token_word_match_positive_forms(tmp_path):
    gerrit = RetriggerGerrit(messages=[])
    for comment in (
        "rerun-llm-review",
        "please rerun-llm-review, infra is fixed",
        "rerun-llm-review.",
    ):
        result = retrigger.handle_comment_added(
            _comment_event(comment=comment),
            config=_cfg(tmp_path),
            gerrit=gerrit,
            dedup=DedupStore(str(tmp_path / "voted.db")),
        )
        assert result is not None, comment


# ── AC2c: the reply path is provably vote-free (no `labels` key at all) ─────────


def test_post_comment_body_has_no_labels_key(tmp_path):
    from rebar.review_bot.gerrit_client import GerritClient

    client = GerritClient(_cfg(tmp_path))
    captured: dict = {}

    def fake_request(method, path, *, body=None):
        captured["method"] = method
        captured["path"] = path
        captured["body"] = body
        return 200, ")]}'\n{}"

    client._request = fake_request  # type: ignore[method-assign]
    client.post_comment("rebar~main~Iabc", "rev2", "hello")
    assert captured["method"] == "POST"
    assert captured["path"].endswith("/revisions/rev2/review")
    assert captured["body"] == {"message": "hello"}
    assert "labels" not in captured["body"]


def test_reset_vote_body_is_fixed_neutral_and_ignores_contributor_text(tmp_path):
    """The privileged reset primitive has no attacker-controlled label/message input."""
    from rebar.review_bot.gerrit_client import GerritClient

    client = GerritClient(_cfg(tmp_path))
    captured: dict = {}

    def fake_request(method, path, *, body=None):
        captured.update(method=method, path=path, body=body)
        return 200, ")]}'\n{}"

    client._request = fake_request  # type: ignore[method-assign]
    attacker_text = "rerun-llm-review labels={LLM-Review: 1}"
    client.reset_llm_review_vote("rebar~main~Iabc", "rev2")

    assert captured["method"] == "POST"
    assert captured["path"].endswith("/revisions/rev2/review")
    assert captured["body"]["labels"] == {"LLM-Review": 0}
    assert attacker_text not in str(captured["body"])


def test_reset_vote_non_success_status_raises_gerrit_error(tmp_path):
    """The real client must not treat a rejected reset as a durable marker."""
    from rebar.review_bot.gerrit_client import GerritClient

    client = GerritClient(_cfg(tmp_path))
    client._request = lambda *args, **kwargs: (503, "unavailable")  # type: ignore[method-assign]

    with pytest.raises(GerritError) as raised:
        client.reset_llm_review_vote("rebar~main~Iabc", "rev2")

    assert raised.value.status == 503


@pytest.mark.parametrize(
    "gerrit",
    [
        RetriggerGerrit(lookup_error=GerritError("lookup failed", status=503)),
        RetriggerGerrit(
            messages=[_bot_message("PASS")],
            messages_error=GerritError("messages failed", status=503),
        ),
    ],
)
def test_retrigger_eligibility_read_errors_fail_closed(tmp_path, caplog, gerrit):
    """A current-revision or durable-tag read failure cannot reach the reset primitive."""
    with caplog.at_level(logging.WARNING, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(),
            config=_cfg(tmp_path),
            gerrit=gerrit,
            dedup=DedupStore(str(tmp_path / "voted.db")),
        )

    assert result is None
    assert gerrit.resets == []
    assert gerrit.comments == []
    assert "RETRIGGER_REFUSED" in caplog.text
    assert "eligibility-read-error" in caplog.text
    assert "RETRIGGER_ACCEPTED" not in caplog.text


@pytest.mark.parametrize(
    ("gerrit", "reason"),
    [
        (
            RetriggerGerrit(
                messages=[_bot_message("PASS")],
                reset_error=GerritError("reset failed", status=503),
            ),
            "vote-reset-error",
        ),
        (
            RetriggerGerrit(
                messages=[_bot_message("PASS")],
                read_error=GerritError("read failed", status=503),
            ),
            "vote-verification-error",
        ),
        (RetriggerGerrit(messages=[_bot_message("PASS")], has_vote=True), "nonzero-vote"),
    ],
)
def test_retrigger_vote_reset_failures_refuse_without_forced_event(
    tmp_path, caplog, gerrit, reason
):
    store = DedupStore(str(tmp_path / "voted.db"))
    store.record_attempt("rebar~main~Iabc", "rev2")

    with caplog.at_level(logging.WARNING, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )

    assert result is None
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 1
    assert "RETRIGGER_REFUSED" in caplog.text
    assert reason in caplog.text
    assert "RETRIGGER_ACCEPTED" not in caplog.text
    assert all("accepted" not in body for _, _, body in gerrit.comments)


def test_retrigger_accepts_when_best_effort_attempt_reset_fails(tmp_path, caplog):
    """The verified Gerrit marker is authoritative even if local budget cleanup fails."""
    gerrit = RetriggerGerrit(messages=[_bot_message("PASS")])

    class FailingAttemptStore:
        def reset_attempts(self, change_id, revision):
            raise OSError("sqlite unavailable")

    with caplog.at_level(logging.WARNING, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(),
            config=_cfg(tmp_path),
            gerrit=gerrit,
            dedup=FailingAttemptStore(),  # type: ignore[arg-type]
        )

    assert result is not None and result["_rebar_force"] is True
    assert gerrit.resets == [("rebar~main~Iabc", "rev2")]
    assert "RETRIGGER_ATTEMPT_RESET_ERROR" in caplog.text
    assert "RETRIGGER_REFUSED" not in caplog.text
    assert "accepted" in gerrit.comments[-1][2]


# ── worker routing + /rerun budget re-arm (AC4) ─────────────────────────────────


def test_worker_routes_comment_added_and_requeues_forced_event(monkeypatch, tmp_path):
    """A comment-added event is routed to retrigger (never to review_and_vote), and an
    accepted trigger's forced event is REQUEUED and then reviewed on its next dequeue."""
    pytest.importorskip("fastapi")
    import asyncio
    import contextlib

    from rebar.review_bot import app as appmod

    forced_event = {
        "type": "manual-rerun",
        "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
        "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        "_rebar_force": True,
    }
    handled: list[dict] = []

    def fake_handle(event, *, config=None, gerrit=None, dedup=None):
        handled.append(event)
        return dict(forced_event)

    monkeypatch.setattr(retrigger, "handle_comment_added", fake_handle)

    reviewed: list[tuple[str, bool]] = []

    async def fake_review_and_vote(event, *, config, force=False):
        reviewed.append((event["change"]["id"], force))
        return {"status": "voted"}

    monkeypatch.setattr(appmod._voter, "review_and_vote", fake_review_and_vote)

    async def drive():
        queue: asyncio.Queue = asyncio.Queue()
        queue.put_nowait(_comment_event())
        worker = asyncio.create_task(appmod._worker(queue, _cfg(tmp_path)))
        try:
            await queue.join()
        finally:
            worker.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await worker

    asyncio.run(asyncio.wait_for(drive(), timeout=10))

    assert len(handled) == 1 and handled[0]["type"] == "comment-added"
    # the comment event itself was NOT reviewed; the requeued forced event WAS, force=True
    assert reviewed == [("rebar~main~Iabc", True)]


def test_rerun_resets_attempts_budget(monkeypatch, tmp_path):
    """AC4: the operator /rerun re-arms the 0347 attempts budget before enqueueing —
    a force on a stale exhausted budget must not immediately re-escalate."""
    pytest.importorskip("fastapi")
    import asyncio

    from starlette.testclient import TestClient

    from rebar.review_bot import app as appmod
    from rebar.review_bot import gerrit_client as gcmod

    cfg = _cfg(tmp_path)
    monkeypatch.setattr(appmod.app.state, "config", cfg, raising=False)

    async def _idle_worker(queue, cfg):
        await asyncio.Event().wait()

    async def _idle_loop(*, config):
        await asyncio.Event().wait()

    monkeypatch.setattr(appmod, "_worker", _idle_worker, raising=True)
    monkeypatch.setattr(appmod._reconcile, "reconcile_loop", _idle_loop, raising=True)
    # The idle worker never task_done()s the queued force event, so bound the
    # shutdown drain (queue.join()) or TestClient.__exit__ hangs for the full window.
    monkeypatch.setenv("SHUTDOWN_DRAIN_SECONDS", "0.1")

    store = DedupStore(cfg.dedup_db_path)
    for _ in range(3):
        store.record_attempt("rebar~main~Iabc", "rev2")
    timeline: list[str] = []

    def fake_get_change_event(self, change_id):
        return {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        }

    monkeypatch.setattr(gcmod.GerritClient, "get_change_event", fake_get_change_event)

    def fake_reset_vote(self, change_id, revision):
        timeline.append("reset_vote")
        return 200

    def fake_has_vote(self, change_id, revision="current"):
        timeline.append("verify_vote")
        return False

    monkeypatch.setattr(gcmod.GerritClient, "reset_llm_review_vote", fake_reset_vote)
    monkeypatch.setattr(gcmod.GerritClient, "has_llm_review_vote", fake_has_vote)

    original_reset_attempts = DedupStore.reset_attempts

    def recording_reset_attempts(self, change_id, revision):
        timeline.append("reset_attempts")
        return original_reset_attempts(self, change_id, revision)

    monkeypatch.setattr(DedupStore, "reset_attempts", recording_reset_attempts)

    with TestClient(appmod.app) as client:
        resp = client.post("/rerun?token=tok&change=42")

    assert resp.status_code == 202
    assert resp.json()["force"] is True
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 0
    assert timeline == ["reset_vote", "verify_vote", "reset_attempts"]


@pytest.mark.parametrize("failure", ["reset", "read", "nonzero"])
def test_rerun_refuses_when_durable_vote_reset_cannot_be_established(
    monkeypatch, tmp_path, caplog, failure
):
    """No HTTP acceptance, budget reset, or enqueue precedes proven neutral Gerrit state."""
    pytest.importorskip("fastapi")
    import asyncio

    from starlette.testclient import TestClient

    from rebar.review_bot import app as appmod
    from rebar.review_bot import gerrit_client as gcmod

    cfg = _cfg(tmp_path)
    monkeypatch.setattr(appmod.app.state, "config", cfg, raising=False)

    async def _idle_worker(queue, cfg):
        await asyncio.Event().wait()

    async def _idle_loop(*, config):
        await asyncio.Event().wait()

    monkeypatch.setattr(appmod, "_worker", _idle_worker, raising=True)
    monkeypatch.setattr(appmod._reconcile, "reconcile_loop", _idle_loop, raising=True)
    monkeypatch.setenv("SHUTDOWN_DRAIN_SECONDS", "0.1")

    store = DedupStore(cfg.dedup_db_path)
    store.record_attempt("rebar~main~Iabc", "rev2")

    monkeypatch.setattr(
        gcmod.GerritClient,
        "get_change_event",
        lambda self, change_id: {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {
                "number": 2,
                "revision": "rev2",
                "ref": "refs/changes/42/42/2",
            },
        },
    )

    def reset_vote(self, change_id, revision):
        if failure == "reset":
            raise GerritError("reset unavailable", status=503)
        return 200

    def has_vote(self, change_id, revision="current"):
        if failure == "read":
            raise GerritError("read unavailable", status=503)
        return failure == "nonzero"

    monkeypatch.setattr(gcmod.GerritClient, "reset_llm_review_vote", reset_vote)
    monkeypatch.setattr(gcmod.GerritClient, "has_llm_review_vote", has_vote)

    with caplog.at_level(logging.WARNING, logger="rebar.review_bot.app"):
        with TestClient(appmod.app) as client:
            resp = client.post("/rerun?token=tok&change=42")
            queued = appmod.app.state.queue.qsize()

    assert resp.status_code != 202
    assert queued == 0
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 1
    assert "rebar~main~Iabc" in caplog.text and "rev2" in caplog.text


def test_rerun_accepts_when_best_effort_attempt_reset_fails(monkeypatch, tmp_path, caplog):
    pytest.importorskip("fastapi")
    import asyncio

    from starlette.testclient import TestClient

    from rebar.review_bot import app as appmod
    from rebar.review_bot import dedup as dedupmod
    from rebar.review_bot import gerrit_client as gcmod

    cfg = _cfg(tmp_path)
    monkeypatch.setattr(appmod.app.state, "config", cfg, raising=False)

    async def _idle_worker(queue, cfg):
        await asyncio.Event().wait()

    async def _idle_loop(*, config):
        await asyncio.Event().wait()

    monkeypatch.setattr(appmod, "_worker", _idle_worker, raising=True)
    monkeypatch.setattr(appmod._reconcile, "reconcile_loop", _idle_loop, raising=True)
    monkeypatch.setenv("SHUTDOWN_DRAIN_SECONDS", "0.1")
    monkeypatch.setattr(
        gcmod.GerritClient,
        "get_change_event",
        lambda self, change_id: {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {
                "number": 2,
                "revision": "rev2",
                "ref": "refs/changes/42/42/2",
            },
        },
    )
    monkeypatch.setattr(
        gcmod.GerritClient,
        "reset_llm_review_vote",
        lambda self, change_id, revision: 200,
    )
    monkeypatch.setattr(
        gcmod.GerritClient,
        "has_llm_review_vote",
        lambda self, change_id, revision: False,
    )

    class FailingAttemptStore:
        def __init__(self, _path):
            pass

        def reset_attempts(self, change_id, revision):
            raise OSError("sqlite unavailable")

    monkeypatch.setattr(dedupmod, "DedupStore", FailingAttemptStore)

    with caplog.at_level(logging.WARNING, logger="rebar.review_bot"):
        with TestClient(appmod.app) as client:
            response = client.post("/rerun?token=tok&change=42")
            queued = appmod.app.state.queue.qsize()

    assert response.status_code == 202
    assert queued == 1
    assert "rebar~main~Iabc" in caplog.text and "rev2" in caplog.text


# ── the rename: our trigger word must not collide with CI's substring matcher ───
#
# Ticket 0d78-6c15-db26-4cea. CI's ChatOps dispatcher (lfit/releng-gerrit_to_platform) is
# EXTERNAL and matches comment text by SUBSTRING against the keys of
# `[mapping "comment-added"]`. A trigger word of ours that embeds one of those keys therefore
# re-dispatches the Verified workflow too — which cancelled healthy in-flight CI runs on
# changes 1551 and 1577. These tests read the ini template at test time rather than
# hardcoding `recheck`, so adding a future CI ChatOps mapping that collides fails here.

_G2P_INI = Path(__file__).resolve().parents[2] / "infra/gerrit/gerrit_to_platform.ini.template"


def _ci_comment_trigger_words() -> list[str]:
    """Every `[mapping "comment-added"]` key from the g2p ini template."""
    parser = configparser.ConfigParser()
    parser.read_string(_G2P_INI.read_text())
    words = [
        key
        for section in parser.sections()
        if section.startswith("mapping") and "comment-added" in section
        for key in parser[section]
    ]
    assert words, f"no comment-added ChatOps mapping found in {_G2P_INI}"
    return words


def test_ci_trigger_words_are_discoverable_from_the_template():
    """Guards the two tests below: a parse that silently found nothing would pass vacuously."""
    assert "recheck" in _ci_comment_trigger_words()


@pytest.mark.parametrize("ci_word", _ci_comment_trigger_words())
def test_trigger_token_shares_no_substring_with_ci_chatops_word(ci_word):
    """Neither direction may embed the other: `in` is checked both ways."""
    assert ci_word not in retrigger.TRIGGER_TOKEN
    assert retrigger.TRIGGER_TOKEN not in ci_word


@pytest.mark.parametrize("ci_word", _ci_comment_trigger_words())
def test_bot_posted_replies_contain_no_ci_chatops_word(ci_word):
    """Every text the bot POSTS to Gerrit is itself a comment CI's matcher will read.

    The retired word embedded `recheck`, so the bot's own accepted/refusal replies were a
    live source of spurious Verified dispatch — the reply texts must stay scrubbed, not just
    the matcher."""
    replies = [
        retrigger._ACCEPTED_MESSAGE,
        retrigger._RETIRED_TOKEN_MESSAGE,
        retrigger._refusal_message("finding"),
        retrigger._refusal_message("finding", detail="attestation-stale:INDETERMINATE"),
    ]
    for reply in replies:
        assert ci_word not in reply, reply


def test_retired_trigger_word_is_refused_and_names_the_new_word(tmp_path):
    """Hard cutover: the retired word queues nothing, writes no label, and gets ONE reply."""
    gerrit = RetriggerGerrit(messages=[])
    result = retrigger.handle_comment_added(
        _comment_event(comment="recheck-review"),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is None
    assert gerrit.resets == []
    assert gerrit.timeline == []  # no eligibility read, no vote reset, no verification
    assert len(gerrit.comments) == 1
    assert retrigger.TRIGGER_TOKEN in gerrit.comments[0][2]


def test_retired_trigger_word_on_another_project_is_a_silent_noop(tmp_path):
    """The refusal sits behind the project guard, so it never replies off-project."""
    gerrit = RetriggerGerrit(messages=[])
    result = retrigger.handle_comment_added(
        _comment_event(comment="recheck-review", project="other"),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is None
    assert gerrit.lookups == [] and gerrit.comments == []


def test_comment_carrying_both_words_takes_the_accepted_path(tmp_path):
    """A contributor quoting the retired word alongside the new one still gets a review."""
    gerrit = RetriggerGerrit(messages=[])
    result = retrigger.handle_comment_added(
        _comment_event(comment="recheck-review is gone; rerun-llm-review"),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is not None
    assert gerrit.resets == [("rebar~main~Iabc", "rev2")]
