"""Held-out oracle for scripts/check_build_env_locked.py (story 08a8).

The guard closes the ambient-package hole under `--no-isolation --no-deps`: it parses the
installed set (from `pip freeze`, lowercased name->version) and the lock's `name==version`
entries (skipping `--hash`/comment lines), and FAILS (non-zero) if any installed package is
absent from the lock OR version-mismatched — modulo a documented base allowlist
({pip, setuptools, wheel}). A raw text diff of the two file formats would be meaningless;
this is a parsed comparison.

Interface (contract): `python scripts/check_build_env_locked.py --lock <lock> --freeze <freeze>`
exits 0 when the installed set is lock-consistent (allowlist aside), non-zero otherwise, and
prints the offending package(s) to stderr.

Tests assert OBSERVABLE behaviour: process exit code + stderr — never internals.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import rebar

SCRIPT = Path(rebar.__file__).resolve().parents[2] / "scripts" / "check_build_env_locked.py"

# A minimal hash-locked lock file (name==version + --hash lines + comments, like pip-compile).
LOCK = """\
# generated by pip-compile --generate-hashes
build==1.2.2.post1 \\
    --hash=sha256:aaaa
hatchling==1.27.0 \\
    --hash=sha256:bbbb
twine==6.1.0 \\
    --hash=sha256:cccc
"""


def _run(lock_text: str, freeze_text: str, tmp_path: Path) -> subprocess.CompletedProcess:
    lock = tmp_path / "release-requirements.txt"
    freeze = tmp_path / "freeze.txt"
    lock.write_text(lock_text)
    freeze.write_text(freeze_text)
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--lock", str(lock), "--freeze", str(freeze)],
        capture_output=True,
        text=True,
    )


# ── HAPPY PATH (implementer sees) ─────────────────────────────────────────────
def test_clean_env_passes(tmp_path: Path) -> None:
    # Installed set == lock (+ allowlisted base pkgs) -> exit 0.
    freeze = (
        "build==1.2.2.post1\nhatchling==1.27.0\ntwine==6.1.0\n"
        "pip==24.0\nsetuptools==70.0\nwheel==0.43\n"
    )
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode == 0, f"clean env should pass: {cp.stdout}{cp.stderr}"


# ══════════════════════════════════════════════════════════════════════════════
#  HELD-OUT ORACLE (edge cases)
# ══════════════════════════════════════════════════════════════════════════════
def test_extra_unlocked_package_fails(tmp_path: Path) -> None:
    # An installed package absent from the lock (and not allowlisted) -> non-zero.
    freeze = "build==1.2.2.post1\nhatchling==1.27.0\ntwine==6.1.0\nrequests==2.32.0\n"
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode != 0, "an unlocked extra package must fail the guard"
    assert "requests" in (cp.stdout + cp.stderr).lower()


def test_version_mismatch_fails(tmp_path: Path) -> None:
    # An installed package at a different version than the lock -> non-zero.
    freeze = "build==1.2.2.post1\nhatchling==9.9.9\ntwine==6.1.0\n"
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode != 0, "a version mismatch must fail the guard"
    assert "hatchling" in (cp.stdout + cp.stderr).lower()


def test_base_allowlist_extras_pass(tmp_path: Path) -> None:
    # pip/setuptools/wheel are allowlisted even when absent from the lock -> exit 0.
    freeze = (
        "build==1.2.2.post1\nhatchling==1.27.0\ntwine==6.1.0\n"
        "pip==24.0\nsetuptools==70.0\nwheel==0.43\n"
    )
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode == 0, f"allowlisted base pkgs must not fail: {cp.stderr}"


def test_case_insensitive_name_match(tmp_path: Path) -> None:
    # Names compare case-insensitively (pip freeze may differ in case).
    freeze = "Build==1.2.2.post1\nHatchling==1.27.0\nTwine==6.1.0\n"
    cp = _run(LOCK, freeze, tmp_path)
    assert cp.returncode == 0, f"name match must be case-insensitive: {cp.stderr}"
