"""Tests for the contributor-triggerable re-review (``recheck-review``, ticket bb9b).

The security property under test: a ``recheck-review`` comment can NEVER write a vote
and can NEVER get a real findings-BLOCK re-reviewed — only infrastructure states (every
coverage-gap sub-reason, a retries-exhausted escalation, a PASS, a vote-less or
unparseable state) are eligible, decided privileged-side from the bot's own durable
vote-message tag on the CURRENT revision, never from the requesting comment.
"""

from __future__ import annotations

import logging

import pytest

from rebar.review_bot import retrigger
from rebar.review_bot.adapter import _TAG_SUFFIXES
from rebar.review_bot.config import ReceiverConfig
from rebar.review_bot.dedup import DedupStore


def _cfg(tmp_path) -> ReceiverConfig:
    return ReceiverConfig(
        llm_review_max_value=1,
        llm_review_block_value=-1,
        dedup_db_path=str(tmp_path / "voted.db"),
        gerrit_bot_token="tok",
        webhook_token="tok",
        project="rebar",
        bot_user="rebar-review-bot",
    )


def _comment_event(
    comment: str = "recheck-review",
    author: str = "contributor",
    project: str = "rebar",
) -> dict:
    return {
        "type": "comment-added",
        "change": {"id": "rebar~main~Iabc", "number": 42, "project": project},
        "patchSet": {"number": 2, "revision": "rev2"},
        "author": {"username": author},
        "comment": f"Patch Set 2:\n\n{comment}",
    }


def _bot_message(tag_body: str, revision_number: int = 2, tag: str = "autogenerated:rebar") -> dict:
    return {
        "_revision_number": revision_number,
        "tag": tag,
        "message": f"Patch Set {revision_number}: LLM-Review-1\n\n[LLM-Review: {tag_body}]\nbody",
    }


class RetriggerGerrit:
    """No-network Gerrit double for the retrigger path: current-revision lookup, the
    change-message list, and the vote-free reply — recording everything posted."""

    def __init__(self, messages: list[dict] | None = None, *, change_exists: bool = True):
        self.messages = messages or []
        self.change_exists = change_exists
        self.comments: list[tuple[str, str, str]] = []
        self.lookups: list[str] = []

    def get_change_event(self, change_id: str) -> dict | None:
        self.lookups.append(change_id)
        if not self.change_exists:
            return None
        return {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        }

    def get_change_messages(self, change_id: str) -> list[dict]:
        return self.messages

    def post_comment(self, change_id: str, revision: str, message: str) -> int:
        self.comments.append((change_id, revision, message))
        return 200


# ── the tag parser covers all three production tag shapes (AC2b) ────────────────


@pytest.mark.parametrize(
    ("tag_body", "expected"),
    [
        # (a) every _TAG_SUFFIXES member, straight from the vocabulary source of truth
        *[
            (
                suffix,
                "pass"
                if reason == "PASS"
                else ("finding" if reason == "finding" else f"coverage-gap:{reason}"),
            )
            for reason, suffix in _TAG_SUFFIXES.items()
        ],
        # (b) the hardcoded merge-review literal (voter._merge_coverage_gap_decision) —
        # NOT a _TAG_SUFFIXES member, must still classify
        ("BLOCK — coverage-gap (merge-review)", "coverage-gap:merge-review"),
        # (c) the in-tag merge-change suffix variant, applied to each stem kind
        ("PASS (merge-change, 3 integrated commit(s))", "pass"),
        ("BLOCK — finding (merge-change, 1 integrated commit(s))", "finding"),
        (
            "BLOCK — coverage-gap (review-error) (merge-change, 2 integrated commit(s))",
            "coverage-gap:review-error",
        ),
        # unknown-but-bracketed → unparseable (eligible, fail-open to a fresh review)
        ("SOMETHING NEW", "unparseable"),
    ],
)
def test_classify_tag_all_production_shapes(tag_body, expected):
    message = f"Patch Set 2: LLM-Review-1\n\n[LLM-Review: {tag_body}]\ntrailing body"
    assert retrigger.classify_tag(message) == expected


def test_classify_tag_absent_returns_none():
    assert retrigger.classify_tag("Patch Set 2:\n\njust words, no tag") is None
    assert retrigger.classify_tag(None) is None


def test_latest_bot_tag_state_filters_revision_and_tag():
    gerrit = RetriggerGerrit(
        messages=[
            _bot_message("BLOCK — finding", revision_number=1),  # OLD revision — ignored
            {"_revision_number": 2, "tag": None, "message": "[LLM-Review: PASS]"},  # not bot
            _bot_message("BLOCK — coverage-gap (review-error)", revision_number=2),
            _bot_message("PASS", revision_number=2),  # newest bot message wins
        ]
    )
    assert retrigger.latest_bot_tag_state(gerrit, "rebar~main~Iabc", 2) == "pass"


# ── AC2: findings-BLOCK is refused — bare AND merge tag forms ───────────────────


@pytest.mark.parametrize(
    "tag_body",
    ["BLOCK — finding", "BLOCK — finding (merge-change, 3 integrated commit(s))"],
)
def test_finding_block_is_refused(tmp_path, caplog, tag_body):
    gerrit = RetriggerGerrit(messages=[_bot_message(tag_body)])
    store = DedupStore(str(tmp_path / "voted.db"))
    store.record_attempt("rebar~main~Iabc", "rev2")

    with caplog.at_level(logging.WARNING, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )

    assert result is None  # no enqueue
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 1  # budget NOT reset
    assert len(gerrit.comments) == 1  # refusal reply posted…
    assert "REAL FINDING" in gerrit.comments[0][2]
    assert "RETRIGGER_REFUSED" in caplog.text
    assert "RETRIGGER_ACCEPTED" not in caplog.text


# ── AC1: eligible states re-arm the budget and enqueue a forced review ──────────


@pytest.mark.parametrize(
    "tag_body",
    [
        "BLOCK — coverage-gap (gate-disabled)",
        "BLOCK — coverage-gap (review-error)",  # incl. a 0347 retries-exhausted escalation
        "BLOCK — coverage-gap (merge-review)",
        "PASS",
    ],
)
def test_eligible_states_accept(tmp_path, caplog, tag_body):
    gerrit = RetriggerGerrit(messages=[_bot_message(tag_body)])
    store = DedupStore(str(tmp_path / "voted.db"))
    # Simulate the 0347 exhausted budget the human trigger must re-arm.
    for _ in range(3):
        store.record_attempt("rebar~main~Iabc", "rev2")

    with caplog.at_level(logging.INFO, logger="rebar.review_bot.retrigger"):
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )

    assert result is not None and result["_rebar_force"] is True
    assert result["patchSet"]["revision"] == "rev2"  # the CURRENT revision, re-anchored
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 0  # budget re-armed
    assert len(gerrit.comments) == 1
    assert "queued" in gerrit.comments[0][2]
    assert "RETRIGGER_ACCEPTED" in caplog.text


def test_voteless_and_unparseable_states_are_eligible(tmp_path):
    for messages in ([], [_bot_message("SOMETHING NEW")]):
        gerrit = RetriggerGerrit(messages=messages)
        store = DedupStore(str(tmp_path / f"voted{len(messages)}.db"))
        result = retrigger.handle_comment_added(
            _comment_event(), config=_cfg(tmp_path), gerrit=gerrit, dedup=store
        )
        assert result is not None and result["_rebar_force"] is True


# ── AC3: loop guard + token no-ops (no Gerrit traffic at all) ───────────────────


def test_bot_own_comment_is_a_noop(tmp_path):
    gerrit = RetriggerGerrit(messages=[_bot_message("BLOCK — coverage-gap (review-error)")])
    result = retrigger.handle_comment_added(
        _comment_event(author="rebar-review-bot"),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is None
    assert gerrit.lookups == [] and gerrit.comments == []


@pytest.mark.parametrize(
    "comment",
    ["please recheck", "recheck", "recheck-reviews", "pre-recheck-review", "recheck-review-x"],
)
def test_non_matching_comment_is_a_noop(tmp_path, comment):
    gerrit = RetriggerGerrit()
    result = retrigger.handle_comment_added(
        _comment_event(comment=comment),
        config=_cfg(tmp_path),
        gerrit=gerrit,
        dedup=DedupStore(str(tmp_path / "voted.db")),
    )
    assert result is None
    assert gerrit.lookups == [] and gerrit.comments == []


def test_token_word_match_positive_forms(tmp_path):
    gerrit = RetriggerGerrit(messages=[])
    for comment in ("recheck-review", "please recheck-review, infra is fixed", "recheck-review."):
        result = retrigger.handle_comment_added(
            _comment_event(comment=comment),
            config=_cfg(tmp_path),
            gerrit=gerrit,
            dedup=DedupStore(str(tmp_path / "voted.db")),
        )
        assert result is not None, comment


# ── AC2c: the reply path is provably vote-free (no `labels` key at all) ─────────


def test_post_comment_body_has_no_labels_key(tmp_path):
    from rebar.review_bot.gerrit_client import GerritClient

    client = GerritClient(_cfg(tmp_path))
    captured: dict = {}

    def fake_request(method, path, *, body=None):
        captured["method"] = method
        captured["path"] = path
        captured["body"] = body
        return 200, ")]}'\n{}"

    client._request = fake_request  # type: ignore[method-assign]
    client.post_comment("rebar~main~Iabc", "rev2", "hello")
    assert captured["method"] == "POST"
    assert captured["path"].endswith("/revisions/rev2/review")
    assert captured["body"] == {"message": "hello"}
    assert "labels" not in captured["body"]


# ── worker routing + /rerun budget re-arm (AC4) ─────────────────────────────────


def test_worker_routes_comment_added_and_requeues_forced_event(monkeypatch, tmp_path):
    """A comment-added event is routed to retrigger (never to review_and_vote), and an
    accepted trigger's forced event is REQUEUED and then reviewed on its next dequeue."""
    pytest.importorskip("fastapi")
    import asyncio
    import contextlib

    from rebar.review_bot import app as appmod

    forced_event = {
        "type": "manual-rerun",
        "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
        "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        "_rebar_force": True,
    }
    handled: list[dict] = []

    def fake_handle(event, *, config=None, gerrit=None, dedup=None):
        handled.append(event)
        return dict(forced_event)

    monkeypatch.setattr(retrigger, "handle_comment_added", fake_handle)

    reviewed: list[tuple[str, bool]] = []

    async def fake_review_and_vote(event, *, config, force=False):
        reviewed.append((event["change"]["id"], force))
        return {"status": "voted"}

    monkeypatch.setattr(appmod._voter, "review_and_vote", fake_review_and_vote)

    async def drive():
        queue: asyncio.Queue = asyncio.Queue()
        queue.put_nowait(_comment_event())
        worker = asyncio.create_task(appmod._worker(queue, _cfg(tmp_path)))
        try:
            await queue.join()
        finally:
            worker.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await worker

    asyncio.run(asyncio.wait_for(drive(), timeout=10))

    assert len(handled) == 1 and handled[0]["type"] == "comment-added"
    # the comment event itself was NOT reviewed; the requeued forced event WAS, force=True
    assert reviewed == [("rebar~main~Iabc", True)]


def test_rerun_resets_attempts_budget(monkeypatch, tmp_path):
    """AC4: the operator /rerun re-arms the 0347 attempts budget before enqueueing —
    a force on a stale exhausted budget must not immediately re-escalate."""
    pytest.importorskip("fastapi")
    import asyncio

    from starlette.testclient import TestClient

    from rebar.review_bot import app as appmod
    from rebar.review_bot import gerrit_client as gcmod

    cfg = _cfg(tmp_path)
    monkeypatch.setattr(appmod.app.state, "config", cfg, raising=False)

    async def _idle_worker(queue, cfg):
        await asyncio.Event().wait()

    async def _idle_loop(*, config):
        await asyncio.Event().wait()

    monkeypatch.setattr(appmod, "_worker", _idle_worker, raising=True)
    monkeypatch.setattr(appmod._reconcile, "reconcile_loop", _idle_loop, raising=True)
    # The idle worker never task_done()s the queued force event, so bound the
    # shutdown drain (queue.join()) or TestClient.__exit__ hangs for the full window.
    monkeypatch.setenv("SHUTDOWN_DRAIN_SECONDS", "0.1")

    store = DedupStore(cfg.dedup_db_path)
    for _ in range(3):
        store.record_attempt("rebar~main~Iabc", "rev2")

    def fake_get_change_event(self, change_id):
        return {
            "type": "manual-rerun",
            "change": {"id": "rebar~main~Iabc", "number": 42, "project": "rebar"},
            "patchSet": {"number": 2, "revision": "rev2", "ref": "refs/changes/42/42/2"},
        }

    monkeypatch.setattr(gcmod.GerritClient, "get_change_event", fake_get_change_event)

    with TestClient(appmod.app) as client:
        resp = client.post("/rerun?token=tok&change=42")

    assert resp.status_code == 202
    assert resp.json()["force"] is True
    assert store.attempt_count("rebar~main~Iabc", "rev2") == 0
