"""Behavioral coverage for the review-bot entrypoint generated by its Dockerfile."""

from __future__ import annotations

import os
import shlex
import subprocess
from pathlib import Path

DOCKERFILE = Path(__file__).resolve().parents[2] / "infra" / "compose" / "Dockerfile.reviewbot"


def _materialize_entrypoint(tmp_path: Path) -> Path:
    source = DOCKERFILE.read_text()
    section = source.split("# Data-capture entrypoint", 1)[1]
    start = section.index("RUN set -eux;")
    final = "    chmod +x /usr/local/bin/reviewbot-entrypoint.sh"
    end = section.index(final, start) + len(final)
    entrypoint = tmp_path / "reviewbot-entrypoint.sh"
    generator = (
        section[start:end]
        .removeprefix("RUN ")
        .replace("/usr/local/bin/reviewbot-entrypoint.sh", shlex.quote(str(entrypoint)))
    )
    subprocess.run(["sh", "-c", generator], check=True, capture_output=True, text=True)
    return entrypoint


def test_generated_entrypoint_runs_ensure_without_tickets_pat(tmp_path: Path) -> None:
    entrypoint = _materialize_entrypoint(tmp_path)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    receipt = tmp_path / "receipt"
    quoted_receipt = shlex.quote(str(receipt))

    ensure = bin_dir / "reviewbot-ensure-tickets.sh"
    ensure.write_text(f"#!/bin/sh\necho ensure >> {quoted_receipt}\n")
    ensure.chmod(0o755)
    git = bin_dir / "git"
    git.write_text("#!/bin/sh\necho 'git unexpectedly called' >&2\nexit 97\n")
    git.chmod(0o755)

    env = dict(os.environ)
    env.pop("REVIEWBOT_TICKETS_PAT", None)
    env.update({"HOME": str(tmp_path / "home"), "PATH": f"{bin_dir}:{env['PATH']}"})
    result = subprocess.run(
        [entrypoint, "sh", "-c", f"echo app >> {quoted_receipt}"],
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert receipt.read_text().splitlines() == ["ensure", "app"]
